import { InboxItemType } from "@/app/(protected)/_inbox/inbox";
import { trashItemType } from "@/app/(protected)/_trash/trash";
import { statsDataItemType } from "@/app/(protected)/dashboard/_components/stats_charts";
import { WorkflowCardType } from "@/app/(protected)/workflows/_components/workflow_card";
import {
  subDays,
  startOfYesterday,
  startOfToday,
  formatISO,
  startOfTomorrow,
} from "date-fns";
import { WORKFLOW_COLORS } from "./colors_utils";
import { folderType } from "@/app/(protected)/workflows/layout";
import { importedFile } from "@/app/(protected)/_settings/import/import_settings";
import {
  ChatReply,
  knowledgeBase,
  RunItemType,
  PhaseItemType,
  userProfile,
  PhaseLog,
  PhaseOutput,
  PhaseInput,
} from "./types";
import { workflowTemplateType } from "@/app/(protected)/templates/_components/template_card";
import {
  Activity,
  Airplay,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Anchor,
  Aperture,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AtSign,
  Award,
  BarChart,
  BarChart2,
  Battery,
  BatteryCharging,
  Bell,
  BellOff,
  Bluetooth,
  Bold,
  Book,
  Bookmark,
  Box,
  Briefcase,
  Calendar,
  Camera,
  CameraOff,
  Cast,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  Circle,
  Clock,
  Cloud,
  CloudDrizzle,
  CloudLightning,
  CloudOff,
  CloudRain,
  CloudSnow,
  Code,
  Coffee,
  Columns,
  Command,
  Compass,
  Copy,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftDown,
  CornerLeftUp,
  CornerRightDown,
  CornerRightUp,
  CornerUpLeft,
  CornerUpRight,
  Cpu,
  CreditCard,
  Crop,
  Crosshair,
  Database,
  Delete,
  Disc,
  Divide,
  DivideCircle,
  DivideSquare,
  DollarSign,
  Download,
  DownloadCloud,
  Droplet,
  Edit,
  Edit2,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  FastForward,
  Feather,
  FileMinus,
  FilePlus,
  FileText,
  Film,
  Filter,
  Flag,
  Folder,
  FolderMinus,
  FolderPlus,
  Frown,
  Gift,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Globe,
  Grid,
  HardDrive,
  Headphones,
  Heart,
  HelpCircle,
  Hexagon,
  Home,
  Info,
  Italic,
  Key,
  Layers,
  Layout,
  LifeBuoy,
  Link,
  Link2,
  List,
  Loader,
  LogIn,
  LogOut,
  LucideIcon,
  Mail,
  MapPin,
  Maximize,
  Maximize2,
  Meh,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  MicOff,
  Minimize,
  Minimize2,
  Minus,
  MinusCircle,
  MinusSquare,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  MousePointer,
  Move,
  Music,
  Navigation,
  Navigation2,
  Octagon,
  Package,
  Paperclip,
  Pause,
  PauseCircle,
  PenTool,
  Percent,
  Phone,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  PieChart,
  Play,
  PlayCircle,
  Plus,
  PlusCircle,
  PlusSquare,
  Power,
  Printer,
  Radio,
  RefreshCcw,
  RefreshCw,
  Repeat,
  Rewind,
  RotateCcw,
  RotateCw,
  Rss,
  Save,
  Scissors,
  Search,
  Send,
  Settings,
  Share,
  Share2,
  Shield,
  ShieldOff,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sidebar,
  SkipBack,
  SkipForward,
  Slash,
  Sliders,
  Smartphone,
  Smile,
  Speaker,
  Square,
  Star,
  StopCircle,
  Sun,
  Sunrise,
  Sunset,
  Tablet,
  Tag,
  Target,
  Terminal,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  ToggleLeft,
  ToggleRight,
  Trash2,
  TrendingDown,
  TrendingUp,
  Triangle,
  Truck,
  Tv,
  Type,
  Umbrella,
  Underline,
  Unlock,
  Upload,
  UploadCloud,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  UserX,
  Users,
  Video,
  VideoOff,
  Voicemail,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Watch,
  Wifi,
  WifiOff,
  Wind,
  X,
  XCircle,
  XOctagon,
  XSquare,
  Zap,
  ZapOff,
  ZoomIn,
  ZoomOut,
} from "lucide-react";
import { WorkflowTemplatePreview } from "@/components/global/workflow_template_preview";
import { ChatItemType } from "@/app/(protected)/chats/chats_pansidebar";
import { DateRange } from "react-day-picker";
import { generateAvatar } from "./image_utils";
import { getRandomElement } from "./numbers_utils";

export const generateWorkflowLogo = () => {
  const IconName = getRandomElement(lucideIconNames);

  return (
    <IconName className="text-white stroke-white stroke-4 h-fill w-fill" />
  );
};

export const getStatsData = (
  periodSelected: DateRange | undefined,
  workflowsSelected: string[]
) => {
  const dateFrom = periodSelected?.from ?? startOfToday();
  const dateTo = periodSelected?.to ?? startOfTomorrow();

  // Get only data from workflows selected
  const onlyWorkflowSelectedObj = Object.fromEntries(
    Object.entries(statsData).filter(([n, vals]) =>
      workflowsSelected.includes(n)
    )
  );

  // Get only stats whose dates are within the period selected
  const onlyDatesSelectedArr = Object.values(onlyWorkflowSelectedObj)
    .flatMap((i) => i)
    .filter(
      (val) =>
        val.date.getTime() >= dateFrom.getTime() &&
        val.date.getTime() <= dateTo.getTime()
    );

  // Reduce the date, and merge data of same dates
  const mergedDates = Object.values(
    onlyDatesSelectedArr.reduce((acc, curr) => {
      const key = formatISO(curr.date);

      if (!acc[key]) {
        acc[key] = { ...curr };
      } else {
        acc[key].workflow_execution_succeed += curr.workflow_execution_succeed;
        acc[key].workflow_execution_failed += curr.workflow_execution_failed;
        acc[key].phase_execution_succeed += curr.phase_execution_succeed;
        acc[key].phase_execution_failed += curr.phase_execution_failed;
        acc[key].phase_credit_succeed += curr.phase_credit_succeed;
        acc[key].phase_credit_failed += curr.phase_credit_failed;
      }

      return acc;
    }, {} as Record<string, (typeof onlyDatesSelectedArr)[number]>)
  );

  return mergedDates.sort((a, b) => a.date.getTime() - b.date.getTime());
};

export const statsNumber = (
  periodSelected: DateRange | undefined,
  workflowsSelected: string[]
) => {
  if (workflowsSelected.length === 0 || periodSelected === undefined) {
    return {
      workflow_execution_number: null,
      phase_execution_number: null,
      phase_credit_succeed: null,
    };
  }
  const sum = getStatsData(periodSelected, workflowsSelected).reduce(
    (acc, curr) => {
      acc.workflow_execution_number +=
        curr.workflow_execution_succeed + curr.workflow_execution_failed;
      acc.phase_execution_number +=
        curr.phase_execution_succeed + curr.phase_execution_failed;

      acc.phase_credit_succeed += curr.phase_credit_succeed;

      return acc;
    },
    {
      workflow_execution_number: 0,
      phase_execution_number: 0,
      phase_credit_succeed: 0,
    }
  );

  return {
    workflow_execution_number: sum.workflow_execution_number,
    phase_execution_number: sum.phase_execution_number,
    phase_credit_succeed: sum.phase_credit_succeed,
  };
};

export const fakeBigJSON = {
  label: "Main Output",
  type: "JSON",
  value: {
    id: "out_123456",
    timestamp: "2025-03-30T12:45:00Z",
    status: "completed",
    user: {
      id: "user_789",
      name: "John Doe",
      email: "john.doe@example.com",
      preferences: {
        notifications: true,
        theme: "dark",
        language: "en",
        security: {
          twoFactorAuth: true,
          backupCodes: ["A1B2C3", "D4E5F6", "G7H8I9"],
        },
      },
    },
    workflow: {
      id: "wf_001",
      name: "E-commerce Order Processing",
      steps: [
        {
          stepId: "step_1",
          name: "Fetch Order Details",
          durationMs: 1200,
          output: {
            orderId: "ORD_1001",
            customer: {
              id: "cust_456",
              name: "Alice Brown",
              email: "alice@example.com",
            },
            items: [
              {
                itemId: "item_001",
                name: "Smartphone",
                quantity: 1,
                price: 699.99,
                metadata: {
                  brand: "TechBrand",
                  model: "X1000",
                  specs: {
                    storage: "128GB",
                    color: "Black",
                    battery: "4000mAh",
                  },
                },
              },
              {
                itemId: "item_002",
                name: "Wireless Earbuds",
                quantity: 1,
                price: 129.99,
                metadata: {
                  brand: "AudioTech",
                  color: "White",
                  features: {
                    noiseCancellation: true,
                    batteryLife: "24h",
                  },
                },
              },
            ],
          },
        },
        {
          stepId: "step_2",
          name: "Payment Verification",
          durationMs: 800,
          output: {
            paymentStatus: "approved",
            transactionId: "TXN_78910",
            method: "Credit Card",
            card: {
              type: "Visa",
              last4: "1234",
              expiry: "12/27",
              billingAddress: {
                street: "123 Elm St",
                city: "Metropolis",
                zip: "54321",
                country: "USA",
              },
            },
          },
        },
        {
          stepId: "step_3",
          name: "Order Fulfillment",
          durationMs: 1500,
          output: {
            warehouse: {
              id: "WH_03",
              location: "Los Angeles",
              itemsPacked: [
                {
                  itemId: "item_001",
                  status: "Packed",
                },
                {
                  itemId: "item_002",
                  status: "Packed",
                },
              ],
            },
            shipping: {
              carrier: "FastShip",
              trackingNumber: "FS_987654321",
              estimatedDelivery: "2025-04-03T18:00:00Z",
            },
          },
        },
      ],
    },
  },
};

// Array of Lucide icon names
export const lucideIconNames: LucideIcon[] = [
  Activity,
  Airplay,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Anchor,
  Aperture,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AtSign,
  Award,
  BarChart,
  BarChart2,
  Battery,
  BatteryCharging,
  Bell,
  BellOff,
  Bluetooth,
  Bold,
  Book,
  Bookmark,
  Box,
  Briefcase,
  Calendar,
  Camera,
  CameraOff,
  Cast,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  Circle,
  Clock,
  Cloud,
  CloudDrizzle,
  CloudLightning,
  CloudOff,
  CloudRain,
  CloudSnow,
  Code,
  Coffee,
  Columns,
  Command,
  Compass,
  Copy,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftDown,
  CornerLeftUp,
  CornerRightDown,
  CornerRightUp,
  CornerUpLeft,
  CornerUpRight,
  Cpu,
  CreditCard,
  Crop,
  Crosshair,
  Database,
  Delete,
  Disc,
  Divide,
  DivideCircle,
  DivideSquare,
  DollarSign,
  Download,
  DownloadCloud,
  Droplet,
  Edit,
  Edit2,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  FastForward,
  Feather,
  FileMinus,
  FilePlus,
  FileText,
  Film,
  Filter,
  Flag,
  Folder,
  FolderMinus,
  FolderPlus,
  Frown,
  Gift,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Globe,
  Grid,
  HardDrive,
  Headphones,
  Heart,
  HelpCircle,
  Hexagon,
  Home,
  Info,
  Italic,
  Key,
  Layers,
  Layout,
  LifeBuoy,
  Link,
  Link2,
  List,
  Loader,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Maximize,
  Maximize2,
  Meh,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  MicOff,
  Minimize,
  Minimize2,
  Minus,
  MinusCircle,
  MinusSquare,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  MousePointer,
  Move,
  Music,
  Navigation,
  Navigation2,
  Octagon,
  Package,
  Paperclip,
  Pause,
  PauseCircle,
  PenTool,
  Percent,
  Phone,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  PieChart,
  Play,
  PlayCircle,
  Plus,
  PlusCircle,
  PlusSquare,
  Power,
  Printer,
  Radio,
  RefreshCcw,
  RefreshCw,
  Repeat,
  Rewind,
  RotateCcw,
  RotateCw,
  Rss,
  Save,
  Scissors,
  Search,
  Send,
  Settings,
  Share,
  Share2,
  Shield,
  ShieldOff,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sidebar,
  SkipBack,
  SkipForward,
  Slash,
  Sliders,
  Smartphone,
  Smile,
  Speaker,
  Square,
  Star,
  StopCircle,
  Sun,
  Sunrise,
  Sunset,
  Tablet,
  Tag,
  Target,
  Terminal,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  ToggleLeft,
  ToggleRight,
  Trash2,
  TrendingDown,
  TrendingUp,
  Triangle,
  Truck,
  Tv,
  Type,
  Umbrella,
  Underline,
  Unlock,
  Upload,
  UploadCloud,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  UserX,
  Users,
  Video,
  VideoOff,
  Voicemail,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Watch,
  Wifi,
  WifiOff,
  Wind,
  X,
  XCircle,
  XOctagon,
  XSquare,
  Zap,
  ZapOff,
  ZoomIn,
  ZoomOut,
];

export const userEmail = "kabundele@gmail.com";

export const trashItems: trashItemType[] = [
  {
    title: "Email Automation",
    subTitle: "Old marketing campaign flow",
  },
  {
    title: "Client Support - Sarah",
    subTitle: "Archived support conversation",
  },
  { title: "Lead Nurturing", subTitle: "Outdated CRM flow" },
  {
    title: "Project Update - John",
    subTitle: "Weekly project discussion",
  },
  {
    title: "Invoice Reminder",
    subTitle: "Automation for late payments",
  },
  {
    title: "Team Brainstorm",
    subTitle: "Old group chat for Q1 ideas",
  },
  {
    title: "Survey Follow-Up",
    subTitle: "Inactive customer feedback sequence",
  },
  {
    title: "Vendor Inquiry",
    subTitle: "Chat with supplier regarding materials",
  },
  {
    title: "Product Launch Flow",
    subTitle: "Retired campaign for V2",
  },
  {
    title: "Internal QA Discussion",
    subTitle: "Testing feedback conversation",
  },
  {
    title: "Appointment Booking",
    subTitle: "Deprecated calendar sync flow",
  },
  {
    title: "Customer Onboarding - Alex",
    subTitle: "Welcome chat from onboarding",
  },
  {
    title: "Blog Promotion",
    subTitle: "Old social media automation",
  },
  {
    title: "Design Review Chat",
    subTitle: "Archived UI feedback conversation",
  },
  {
    title: "Abandoned Cart Reminder",
    subTitle: "Legacy eCommerce automation",
  },
];

export const inboxItems: InboxItemType[] = [
  {
    date: new Date("2025-03-17T22:00:15"),
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    subjectLine: "Yesss Sarah shared you access to a workflow",
    content: [
      "You have been granted access to a new workflow. Click accept to validate your access",
      "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      "Eos numquam dolorem molestias architecto repudiandae aliquam corporis ipsum temporibus nesciunt minima?",
    ],
    actions: ["view", "accept", "refuse"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-03-16T14:20:30"),
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    subjectLine: "Gogo workflow execution failed: Inventory Management",
    content: [
      "The workflow execution id:40dek9JKsos2sPA failed due to this error: not enough credits.",
    ],
    actions: ["view", "retry"],
    isRead: true,
    isArchived: true,
  },
  {
    date: new Date("2025-03-15T10:15:10"),
    avatar: "https://randomuser.me/api/portraits/women/5.jpg",
    subjectLine: "Sarah shared you access to a workflow",
    content: [
      "A new workflow has been shared with you. Check it out!. ",
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos numquam dolorem molestias architecto repudiandae aliquam corporis ipsum temporibus nesciunt minima? Optio recusandae voluptatibus necessitatibus impedit minus magni quidem, vel dolores. consectetur adipisicing elit.",
      "Eos numquam dolorem molestias architecto repudiandae aliquam corporis ipsum temporibus",
      "nesciunt minima? Optio recusandae voluptatibus necessitatibus impedit minus magni quidem, vel dolores",
    ],
    actions: ["view", "accept", "refuse"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-03-17T20:10:15"),
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
    subjectLine: "Your workflow execution failed: Order Processing",
    content: ["Execution failed due to network errors. Please try again."],
    actions: ["view", "retry"],
    isRead: true,
    isArchived: false,
  },
  {
    date: new Date("2025-03-13T12:10:50"),
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
    subjectLine: "Worflow access accepted",
    content: [
      "You have confirmed your access to the workflow shared by Sarah",
      "Optio recusandae voluptatibus necessitatibus impedit minus magni quidem, vel dolores. consectetur adipisicing elit.",
    ],
    actions: ["view"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-03-12T16:00:40"),
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    subjectLine: "Your workflow execution failed: Payment Gateway",
    content: ["The payment gateway workflow failed. Please check the logs."],
    actions: ["view", "retry"],
    isRead: true,
    isArchived: true,
  },
  {
    date: new Date("2025-03-11T09:30:25"),
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
    subjectLine: "Your workflow execution failed: User Registration",
    content: ["A failure occurred during user registration. Please review."],
    actions: ["view", "retry"],
    isRead: false,
    isArchived: true,
  },
  {
    date: new Date("2025-03-10T17:45:10"),
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
    subjectLine: "Michael shared you access to a workflow",
    content: ["You've been granted access to a workflow related to orders."],
    actions: ["view"],
    isRead: true,
    isArchived: false,
  },
  {
    date: new Date("2025-03-09T11:20:55"),
    avatar: "https://randomuser.me/api/portraits/women/9.jpg",
    subjectLine: "Your workflow execution failed: Inventory Update",
    content: ["The workflow failed due to an error with the database."],
    actions: ["view", "retry"],
    isRead: true,
    isArchived: true,
  },
  {
    date: new Date("2025-03-08T15:50:40"),
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
    subjectLine: "Frank shared you access to a workflow",
    content: ["New workflow has been shared. Please review and proceed."],
    actions: ["view", "accept", "refuse"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-03-07T18:25:10"),
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    subjectLine: "Your workflow execution failed: Report Generation",
    content: ["Failure detected in report generation. Kindly investigate."],
    actions: ["view", "retry"],
    isRead: true,
    isArchived: false,
  },
  {
    date: new Date("2025-03-06T13:40:50"),
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    subjectLine: "Your workflow execution failed: Data Sync",
    content: [
      "The sync operation failed due to data inconsistency.",
      "Optio recusandae voluptatibus necessitatibus impedit minus magni quidem, vel dolores. consectetur adipisicing elit.",
    ],
    actions: ["view", "retry"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-03-04T14:10:30"),
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
    subjectLine: "Your workflow execution succeed: Notification System",
    content: [
      "The notification system workflow has been successfully executed.",
    ],
    actions: [],
    isRead: false,
    isArchived: true,
  },
  {
    date: new Date("2025-03-11T09:45:00"),
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
    subjectLine: "New update on your shared workflow",
    content: ["Workflow ‘User Onboarding’ has received new changes."],
    actions: ["view"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-03-10T11:15:30"),
    avatar: "https://randomuser.me/api/portraits/women/11.jpg",
    subjectLine: "Workflow execution succeeded: Billing Automation",
    content: ["The billing automation executed successfully."],
    actions: ["view"],
    isRead: true,
    isArchived: false,
  },
  {
    date: new Date("2025-03-14T08:05:12"),
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
    subjectLine: "Workflow execution failed: Lead Generation",
    content: ["Credits limit exceeded. Retry after upgrading your plan."],
    actions: ["view", "retry"],
    isRead: false,
    isArchived: true,
  },
  {
    date: new Date("2025-03-09T17:20:45"),
    avatar: "https://randomuser.me/api/portraits/women/10.jpg",
    subjectLine: "Alex granted you access to Workflow Hub",
    content: ["You’ve been added to Workflow Hub. Accept to get started."],
    actions: ["view", "accept", "refuse"],
    isRead: true,
    isArchived: false,
  },
  {
    date: new Date("2025-03-08T19:55:21"),
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
    subjectLine: "Reminder: Pending workflow access request",
    content: ["You have not yet accepted the shared workflow access."],
    actions: ["view", "accept", "refuse"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-03-06T13:35:10"),
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    subjectLine: "Workflow execution failed: Data Sync",
    content: ["Failure in syncing external data sources."],
    actions: ["view", "retry"],
    isRead: false,
    isArchived: true,
  },
  {
    date: new Date("2025-03-05T10:25:00"),
    avatar: "https://randomuser.me/api/portraits/men/10.jpg",
    subjectLine: "System update: Improved workflow builder",
    content: [
      "New drag and drop features added.",
      "You can now organize steps visually.",
    ],
    actions: ["view"],
    isRead: true,
    isArchived: false,
  },
  {
    date: new Date("2025-03-04T22:05:00"),
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
    subjectLine: "You’ve been mentioned in a workflow comment",
    content: ["@You Please review the last execution details."],
    actions: ["view"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-03-03T09:00:00"),
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
    subjectLine: "Reminder: Archive unused workflows",
    content: ["You have 5 workflows inactive for 30+ days."],
    actions: ["view"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-03-02T14:40:00"),
    avatar: "https://randomuser.me/api/portraits/women/1.jpg",
    subjectLine: "Team workflow shared with you: Analytics Reports",
    content: [
      "You’ve been granted access by Daniel.",
      "View and collaborate on this analytics workflow.",
    ],
    actions: ["view", "accept", "refuse"],
    isRead: true,
    isArchived: true,
  },
  {
    date: new Date("2025-03-01T15:45:50"),
    avatar: "https://randomuser.me/api/portraits/men/8.jpg",
    subjectLine: "Workflow execution alert: Email Campaign",
    content: ["Execution took longer than expected."],
    actions: ["view", "retry"],
    isRead: true,
    isArchived: false,
  },
  {
    date: new Date("2025-02-29T18:30:00"),
    avatar: "https://randomuser.me/api/portraits/women/7.jpg",
    subjectLine: "You were removed from a shared workflow",
    content: ["Your access to workflow ‘Daily Report’ was revoked."],
    actions: ["view"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-02-28T21:15:10"),
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
    subjectLine: "Workflow archive confirmation",
    content: ["You successfully archived ‘Monthly Sync’ workflow."],
    actions: ["view"],
    isRead: true,
    isArchived: true,
  },
  {
    date: new Date("2025-02-27T11:50:00"),
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    subjectLine: "Workflow update: Trigger conditions",
    content: ["New trigger conditions are now available for your workflows."],
    actions: ["view"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-02-26T08:25:10"),
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    subjectLine: "Security alert: Workflow permissions changed",
    content: ["Permissions for ‘HR Onboarding’ were modified recently."],
    actions: ["view"],
    isRead: false,
    isArchived: true,
  },
  {
    date: new Date("2025-02-25T17:00:45"),
    avatar: "https://randomuser.me/api/portraits/women/9.jpg",
    subjectLine: "Reminder: Accept shared workflow",
    content: ["‘Feedback Loop’ is still waiting for your confirmation."],
    actions: ["view", "accept", "refuse"],
    isRead: true,
    isArchived: false,
  },
  {
    date: new Date("2025-02-24T13:13:30"),
    avatar: "https://randomuser.me/api/portraits/men/12.jpg",
    subjectLine: "Execution failed: CRM Integration",
    content: ["API key invalid. Please verify your CRM integration."],
    actions: ["view", "retry"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-02-23T10:33:00"),
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
    subjectLine: "yoyo",
    content: [
      "Workflow completion: Event Automation. Your event automation completed successfully.",
    ],
    actions: ["view"],
    isRead: true,
    isArchived: true,
  },
  {
    date: new Date("2025-02-22T16:10:00"),
    avatar: "https://randomuser.me/api/portraits/men/13.jpg",
    subjectLine: "Alert: Low success rate in workflow",
    content: [
      "Only 3 of 10 executions succeeded.",
      "Consider reviewing your logic.",
    ],
    actions: ["view", "retry"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-02-21T12:12:12"),
    avatar: "https://randomuser.me/api/portraits/women/14.jpg",
    subjectLine: "You've been invited to join a workflow: Growth Engine",
    content: [
      "David invited you to participate in a new growth automation workflow.",
    ],
    actions: ["view", "accept", "refuse"],
    isRead: false,
    isArchived: false,
  },
];

export const statsData: statsDataItemType = {
  "Order Fulfillment Workflow": [
    {
      date: new Date("2025-03-24"),
      workflow_execution_succeed: 10,
      workflow_execution_failed: 50,
      phase_execution_succeed: 250,
      phase_execution_failed: 30,
      phase_credit_succeed: 900,
      phase_credit_failed: 120,
    },
    {
      date: new Date("2025-03-23"),
      workflow_execution_succeed: 30,
      workflow_execution_failed: 45,
      phase_execution_succeed: 240,
      phase_execution_failed: 35,
      phase_credit_succeed: 950,
      phase_credit_failed: 100,
    },
    {
      date: new Date("2025-03-22"),
      workflow_execution_succeed: 50,
      workflow_execution_failed: 40,
      phase_execution_succeed: 230,
      phase_execution_failed: 40,
      phase_credit_succeed: 1000,
      phase_credit_failed: 80,
    },
    {
      date: new Date("2025-03-21"),
      workflow_execution_succeed: 70,
      workflow_execution_failed: 35,
      phase_execution_succeed: 220,
      phase_execution_failed: 45,
      phase_credit_succeed: 1100,
      phase_credit_failed: 60,
    },
    {
      date: new Date("2025-03-20"),
      workflow_execution_succeed: 40,
      workflow_execution_failed: 30,
      phase_execution_succeed: 210,
      phase_execution_failed: 50,
      phase_credit_succeed: 1200,
      phase_credit_failed: 70,
    },
    {
      date: new Date("2025-03-19"),
      workflow_execution_succeed: 60,
      workflow_execution_failed: 25,
      phase_execution_succeed: 200,
      phase_execution_failed: 55,
      phase_credit_succeed: 1300,
      phase_credit_failed: 60,
    },
    {
      date: new Date("2025-03-18"),
      workflow_execution_succeed: 90,
      workflow_execution_failed: 20,
      phase_execution_succeed: 190,
      phase_execution_failed: 60,
      phase_credit_succeed: 1400,
      phase_credit_failed: 50,
    },
    {
      date: new Date("2025-03-17"),
      workflow_execution_succeed: 50,
      workflow_execution_failed: 25,
      phase_execution_succeed: 180,
      phase_execution_failed: 65,
      phase_credit_succeed: 1300,
      phase_credit_failed: 55,
    },
    {
      date: new Date("2025-03-16"),
      workflow_execution_succeed: 80,
      workflow_execution_failed: 15,
      phase_execution_succeed: 170,
      phase_execution_failed: 70,
      phase_credit_succeed: 1200,
      phase_credit_failed: 65,
    },
    {
      date: new Date("2025-03-15"),
      workflow_execution_succeed: 60,
      workflow_execution_failed: 20,
      phase_execution_succeed: 160,
      phase_execution_failed: 75,
      phase_credit_succeed: 1100,
      phase_credit_failed: 75,
    },
    {
      date: new Date("2025-03-14"),
      workflow_execution_succeed: 70,
      workflow_execution_failed: 15,
      phase_execution_succeed: 150,
      phase_execution_failed: 80,
      phase_credit_succeed: 1000,
      phase_credit_failed: 85,
    },
    {
      date: new Date("2025-03-13"),
      workflow_execution_succeed: 40,
      workflow_execution_failed: 35,
      phase_execution_succeed: 140,
      phase_execution_failed: 85,
      phase_credit_succeed: 900,
      phase_credit_failed: 95,
    },
    {
      date: new Date("2025-03-12"),
      workflow_execution_succeed: 30,
      workflow_execution_failed: 40,
      phase_execution_succeed: 130,
      phase_execution_failed: 90,
      phase_credit_succeed: 800,
      phase_credit_failed: 105,
    },
    {
      date: new Date("2025-03-11"),
      workflow_execution_succeed: 20,
      workflow_execution_failed: 45,
      phase_execution_succeed: 120,
      phase_execution_failed: 95,
      phase_credit_succeed: 700,
      phase_credit_failed: 115,
    },
    {
      date: new Date("2025-03-10"),
      workflow_execution_succeed: 10,
      workflow_execution_failed: 50,
      phase_execution_succeed: 110,
      phase_execution_failed: 100,
      phase_credit_succeed: 600,
      phase_credit_failed: 125,
    },
  ],

  "Inventory Management Automation": [
    {
      date: new Date("2025-03-24"),
      workflow_execution_succeed: 80,
      workflow_execution_failed: 20,
      phase_execution_succeed: 200,
      phase_execution_failed: 30,
      phase_credit_succeed: 1100,
      phase_credit_failed: 100,
    },
    {
      date: new Date("2025-03-23"),
      workflow_execution_succeed: 60,
      workflow_execution_failed: 30,
      phase_execution_succeed: 190,
      phase_execution_failed: 35,
      phase_credit_succeed: 1000,
      phase_credit_failed: 120,
    },
    {
      date: new Date("2025-03-22"),
      workflow_execution_succeed: 90,
      workflow_execution_failed: 15,
      phase_execution_succeed: 180,
      phase_execution_failed: 40,
      phase_credit_succeed: 950,
      phase_credit_failed: 140,
    },
    {
      date: new Date("2025-03-21"),
      workflow_execution_succeed: 70,
      workflow_execution_failed: 25,
      phase_execution_succeed: 170,
      phase_execution_failed: 45,
      phase_credit_succeed: 900,
      phase_credit_failed: 150,
    },
    {
      date: new Date("2025-03-20"),
      workflow_execution_succeed: 80,
      workflow_execution_failed: 20,
      phase_execution_succeed: 160,
      phase_execution_failed: 50,
      phase_credit_succeed: 850,
      phase_credit_failed: 160,
    },
    {
      date: new Date("2025-03-19"),
      workflow_execution_succeed: 60,
      workflow_execution_failed: 30,
      phase_execution_succeed: 150,
      phase_execution_failed: 55,
      phase_credit_succeed: 800,
      phase_credit_failed: 170,
    },
    {
      date: new Date("2025-03-18"),
      workflow_execution_succeed: 100,
      workflow_execution_failed: 10,
      phase_execution_succeed: 140,
      phase_execution_failed: 60,
      phase_credit_succeed: 750,
      phase_credit_failed: 180,
    },
    {
      date: new Date("2025-03-17"),
      workflow_execution_succeed: 90,
      workflow_execution_failed: 15,
      phase_execution_succeed: 130,
      phase_execution_failed: 65,
      phase_credit_succeed: 700,
      phase_credit_failed: 190,
    },
    {
      date: new Date("2025-03-16"),
      workflow_execution_succeed: 110,
      workflow_execution_failed: 5,
      phase_execution_succeed: 120,
      phase_execution_failed: 70,
      phase_credit_succeed: 650,
      phase_credit_failed: 200,
    },
    {
      date: new Date("2025-03-15"),
      workflow_execution_succeed: 120,
      workflow_execution_failed: 10,
      phase_execution_succeed: 110,
      phase_execution_failed: 75,
      phase_credit_succeed: 600,
      phase_credit_failed: 210,
    },
    {
      date: new Date("2025-03-14"),
      workflow_execution_succeed: 90,
      workflow_execution_failed: 20,
      phase_execution_succeed: 100,
      phase_execution_failed: 80,
      phase_credit_succeed: 550,
      phase_credit_failed: 220,
    },
    {
      date: new Date("2025-03-13"),
      workflow_execution_succeed: 80,
      workflow_execution_failed: 30,
      phase_execution_succeed: 90,
      phase_execution_failed: 85,
      phase_credit_succeed: 500,
      phase_credit_failed: 230,
    },
    {
      date: new Date("2025-03-12"),
      workflow_execution_succeed: 70,
      workflow_execution_failed: 35,
      phase_execution_succeed: 80,
      phase_execution_failed: 90,
      phase_credit_succeed: 450,
      phase_credit_failed: 240,
    },
    {
      date: new Date("2025-03-11"),
      workflow_execution_succeed: 60,
      workflow_execution_failed: 40,
      phase_execution_succeed: 70,
      phase_execution_failed: 95,
      phase_credit_succeed: 400,
      phase_credit_failed: 250,
    },
    {
      date: new Date("2025-03-10"),
      workflow_execution_succeed: 50,
      workflow_execution_failed: 45,
      phase_execution_succeed: 60,
      phase_execution_failed: 100,
      phase_credit_succeed: 350,
      phase_credit_failed: 260,
    },
  ],

  "CRM Lead Nurturing Flow": [
    {
      date: new Date("2025-03-24"),
      workflow_execution_succeed: 80,
      workflow_execution_failed: 15,
      phase_execution_succeed: 160,
      phase_execution_failed: 30,
      phase_credit_succeed: 1100,
      phase_credit_failed: 120,
    },
    {
      date: new Date("2025-03-23"),
      workflow_execution_succeed: 90,
      workflow_execution_failed: 10,
      phase_execution_succeed: 150,
      phase_execution_failed: 35,
      phase_credit_succeed: 1000,
      phase_credit_failed: 140,
    },
    {
      date: new Date("2025-03-22"),
      workflow_execution_succeed: 70,
      workflow_execution_failed: 25,
      phase_execution_succeed: 140,
      phase_execution_failed: 40,
      phase_credit_succeed: 950,
      phase_credit_failed: 160,
    },
    {
      date: new Date("2025-03-21"),
      workflow_execution_succeed: 100,
      workflow_execution_failed: 5,
      phase_execution_succeed: 130,
      phase_execution_failed: 45,
      phase_credit_succeed: 900,
      phase_credit_failed: 180,
    },
    {
      date: new Date("2025-03-20"),
      workflow_execution_succeed: 80,
      workflow_execution_failed: 20,
      phase_execution_succeed: 120,
      phase_execution_failed: 50,
      phase_credit_succeed: 850,
      phase_credit_failed: 190,
    },
    {
      date: new Date("2025-03-19"),
      workflow_execution_succeed: 90,
      workflow_execution_failed: 10,
      phase_execution_succeed: 110,
      phase_execution_failed: 55,
      phase_credit_succeed: 800,
      phase_credit_failed: 200,
    },
    {
      date: new Date("2025-03-18"),
      workflow_execution_succeed: 60,
      workflow_execution_failed: 30,
      phase_execution_succeed: 100,
      phase_execution_failed: 60,
      phase_credit_succeed: 750,
      phase_credit_failed: 210,
    },
    {
      date: new Date("2025-03-17"),
      workflow_execution_succeed: 70,
      workflow_execution_failed: 25,
      phase_execution_succeed: 90,
      phase_execution_failed: 65,
      phase_credit_succeed: 700,
      phase_credit_failed: 220,
    },
    {
      date: new Date("2025-03-16"),
      workflow_execution_succeed: 50,
      workflow_execution_failed: 35,
      phase_execution_succeed: 80,
      phase_execution_failed: 70,
      phase_credit_succeed: 650,
      phase_credit_failed: 230,
    },
    {
      date: new Date("2025-03-15"),
      workflow_execution_succeed: 80,
      workflow_execution_failed: 15,
      phase_execution_succeed: 70,
      phase_execution_failed: 75,
      phase_credit_succeed: 600,
      phase_credit_failed: 240,
    },
    {
      date: new Date("2025-03-14"),
      workflow_execution_succeed: 90,
      workflow_execution_failed: 10,
      phase_execution_succeed: 60,
      phase_execution_failed: 80,
      phase_credit_succeed: 550,
      phase_credit_failed: 250,
    },
    {
      date: new Date("2025-03-13"),
      workflow_execution_succeed: 100,
      workflow_execution_failed: 5,
      phase_execution_succeed: 50,
      phase_execution_failed: 85,
      phase_credit_succeed: 500,
      phase_credit_failed: 260,
    },
    {
      date: new Date("2025-03-12"),
      workflow_execution_succeed: 110,
      workflow_execution_failed: 0,
      phase_execution_succeed: 40,
      phase_execution_failed: 90,
      phase_credit_succeed: 450,
      phase_credit_failed: 270,
    },
    {
      date: new Date("2025-03-11"),
      workflow_execution_succeed: 120,
      workflow_execution_failed: 0,
      phase_execution_succeed: 30,
      phase_execution_failed: 95,
      phase_credit_succeed: 400,
      phase_credit_failed: 280,
    },
    {
      date: new Date("2025-03-10"),
      workflow_execution_succeed: 130,
      workflow_execution_failed: 0,
      phase_execution_succeed: 20,
      phase_execution_failed: 100,
      phase_credit_succeed: 350,
      phase_credit_failed: 290,
    },
  ],

  "Customer Feedback Collection": [
    {
      date: new Date("2025-01-06"),
      workflow_execution_succeed: 45,
      workflow_execution_failed: 20,
      phase_execution_succeed: 170,
      phase_execution_failed: 25,
      phase_credit_succeed: 700,
      phase_credit_failed: 100,
    },
    {
      date: new Date("2025-01-13"),
      workflow_execution_succeed: 55,
      workflow_execution_failed: 18,
      phase_execution_succeed: 180,
      phase_execution_failed: 20,
      phase_credit_succeed: 750,
      phase_credit_failed: 90,
    },
    {
      date: new Date("2025-01-19"),
      workflow_execution_succeed: 60,
      workflow_execution_failed: 15,
      phase_execution_succeed: 190,
      phase_execution_failed: 18,
      phase_credit_succeed: 800,
      phase_credit_failed: 85,
    },
    {
      date: new Date("2025-01-27"),
      workflow_execution_succeed: 62,
      workflow_execution_failed: 13,
      phase_execution_succeed: 195,
      phase_execution_failed: 16,
      phase_credit_succeed: 810,
      phase_credit_failed: 80,
    },
    {
      date: new Date("2025-02-03"),
      workflow_execution_succeed: 66,
      workflow_execution_failed: 10,
      phase_execution_succeed: 205,
      phase_execution_failed: 14,
      phase_credit_succeed: 850,
      phase_credit_failed: 70,
    },
    {
      date: new Date("2025-02-09"),
      workflow_execution_succeed: 70,
      workflow_execution_failed: 8,
      phase_execution_succeed: 215,
      phase_execution_failed: 12,
      phase_credit_succeed: 880,
      phase_credit_failed: 60,
    },
    {
      date: new Date("2025-02-15"),
      workflow_execution_succeed: 75,
      workflow_execution_failed: 7,
      phase_execution_succeed: 230,
      phase_execution_failed: 10,
      phase_credit_succeed: 910,
      phase_credit_failed: 55,
    },
    {
      date: new Date("2025-02-21"),
      workflow_execution_succeed: 80,
      workflow_execution_failed: 5,
      phase_execution_succeed: 250,
      phase_execution_failed: 9,
      phase_credit_succeed: 940,
      phase_credit_failed: 45,
    },
    {
      date: new Date("2025-02-28"),
      workflow_execution_succeed: 85,
      workflow_execution_failed: 4,
      phase_execution_succeed: 265,
      phase_execution_failed: 7,
      phase_credit_succeed: 980,
      phase_credit_failed: 40,
    },
    {
      date: new Date("2025-03-03"),
      workflow_execution_succeed: 88,
      workflow_execution_failed: 3,
      phase_execution_succeed: 275,
      phase_execution_failed: 6,
      phase_credit_succeed: 1000,
      phase_credit_failed: 38,
    },
    {
      date: new Date("2025-03-08"),
      workflow_execution_succeed: 90,
      workflow_execution_failed: 3,
      phase_execution_succeed: 285,
      phase_execution_failed: 5,
      phase_credit_succeed: 1030,
      phase_credit_failed: 30,
    },
    {
      date: new Date("2025-03-12"),
      workflow_execution_succeed: 87,
      workflow_execution_failed: 4,
      phase_execution_succeed: 280,
      phase_execution_failed: 6,
      phase_credit_succeed: 1010,
      phase_credit_failed: 32,
    },
    {
      date: new Date("2025-03-16"),
      workflow_execution_succeed: 84,
      workflow_execution_failed: 5,
      phase_execution_succeed: 270,
      phase_execution_failed: 8,
      phase_credit_succeed: 980,
      phase_credit_failed: 40,
    },
    {
      date: new Date("2025-03-19"),
      workflow_execution_succeed: 81,
      workflow_execution_failed: 6,
      phase_execution_succeed: 260,
      phase_execution_failed: 10,
      phase_credit_succeed: 950,
      phase_credit_failed: 45,
    },
    {
      date: new Date("2025-03-22"),
      workflow_execution_succeed: 78,
      workflow_execution_failed: 8,
      phase_execution_succeed: 255,
      phase_execution_failed: 12,
      phase_credit_succeed: 910,
      phase_credit_failed: 55,
    },
  ],

  "Invoice Automation System": [
    {
      date: new Date("2025-01-02"),
      workflow_execution_succeed: 65,
      workflow_execution_failed: 20,
      phase_execution_succeed: 200,
      phase_execution_failed: 25,
      phase_credit_succeed: 950,
      phase_credit_failed: 110,
    },
    {
      date: new Date("2025-01-09"),
      workflow_execution_succeed: 70,
      workflow_execution_failed: 15,
      phase_execution_succeed: 215,
      phase_execution_failed: 20,
      phase_credit_succeed: 980,
      phase_credit_failed: 90,
    },
    {
      date: new Date("2025-01-16"),
      workflow_execution_succeed: 74,
      workflow_execution_failed: 12,
      phase_execution_succeed: 225,
      phase_execution_failed: 18,
      phase_credit_succeed: 1010,
      phase_credit_failed: 85,
    },
    {
      date: new Date("2025-01-23"),
      workflow_execution_succeed: 77,
      workflow_execution_failed: 10,
      phase_execution_succeed: 230,
      phase_execution_failed: 15,
      phase_credit_succeed: 1050,
      phase_credit_failed: 80,
    },
    {
      date: new Date("2025-01-30"),
      workflow_execution_succeed: 80,
      workflow_execution_failed: 8,
      phase_execution_succeed: 240,
      phase_execution_failed: 12,
      phase_credit_succeed: 1080,
      phase_credit_failed: 65,
    },
    {
      date: new Date("2025-02-05"),
      workflow_execution_succeed: 85,
      workflow_execution_failed: 6,
      phase_execution_succeed: 250,
      phase_execution_failed: 10,
      phase_credit_succeed: 1120,
      phase_credit_failed: 50,
    },
    {
      date: new Date("2025-02-11"),
      workflow_execution_succeed: 90,
      workflow_execution_failed: 5,
      phase_execution_succeed: 265,
      phase_execution_failed: 9,
      phase_credit_succeed: 1150,
      phase_credit_failed: 45,
    },
    {
      date: new Date("2025-02-17"),
      workflow_execution_succeed: 94,
      workflow_execution_failed: 4,
      phase_execution_succeed: 275,
      phase_execution_failed: 8,
      phase_credit_succeed: 1200,
      phase_credit_failed: 40,
    },
    {
      date: new Date("2025-02-23"),
      workflow_execution_succeed: 92,
      workflow_execution_failed: 5,
      phase_execution_succeed: 270,
      phase_execution_failed: 9,
      phase_credit_succeed: 1180,
      phase_credit_failed: 42,
    },
    {
      date: new Date("2025-02-29"),
      workflow_execution_succeed: 89,
      workflow_execution_failed: 6,
      phase_execution_succeed: 265,
      phase_execution_failed: 11,
      phase_credit_succeed: 1140,
      phase_credit_failed: 50,
    },
    {
      date: new Date("2025-03-04"),
      workflow_execution_succeed: 86,
      workflow_execution_failed: 7,
      phase_execution_succeed: 260,
      phase_execution_failed: 13,
      phase_credit_succeed: 1110,
      phase_credit_failed: 60,
    },
    {
      date: new Date("2025-03-09"),
      workflow_execution_succeed: 83,
      workflow_execution_failed: 9,
      phase_execution_succeed: 255,
      phase_execution_failed: 14,
      phase_credit_succeed: 1080,
      phase_credit_failed: 70,
    },
    {
      date: new Date("2025-03-13"),
      workflow_execution_succeed: 79,
      workflow_execution_failed: 10,
      phase_execution_succeed: 250,
      phase_execution_failed: 16,
      phase_credit_succeed: 1050,
      phase_credit_failed: 80,
    },
    {
      date: new Date("2025-03-17"),
      workflow_execution_succeed: 76,
      workflow_execution_failed: 11,
      phase_execution_succeed: 240,
      phase_execution_failed: 18,
      phase_credit_succeed: 1020,
      phase_credit_failed: 85,
    },
    {
      date: new Date("2025-03-21"),
      workflow_execution_succeed: 72,
      workflow_execution_failed: 13,
      phase_execution_succeed: 230,
      phase_execution_failed: 20,
      phase_credit_succeed: 990,
      phase_credit_failed: 90,
    },
  ],
};

export const getFakeStatData = () => {
  return [
    {
      date: subDays(Date.now(), 9),
      workflow_execution_succeed: 790,
      workflow_execution_failed: 100,
      phase_execution_succeed: 250,
      phase_execution_failed: 20,
      phase_credit_succeed: 950,
      phase_credit_failed: 55,
    },
    {
      date: subDays(Date.now(), 8),
      workflow_execution_succeed: 900,
      workflow_execution_failed: 359,
      phase_execution_succeed: 120,
      phase_execution_failed: 60,
      phase_credit_succeed: 860,
      phase_credit_failed: 90,
    },
    {
      date: subDays(Date.now(), 7),
      workflow_execution_succeed: 90,
      workflow_execution_failed: 15,
      phase_execution_succeed: 310,
      phase_execution_failed: 22,
      phase_credit_succeed: 1200,
      phase_credit_failed: 50,
    },
    {
      date: subDays(Date.now(), 6),
      workflow_execution_succeed: 25,
      workflow_execution_failed: 50,
      phase_execution_succeed: 80,
      phase_execution_failed: 70,
      phase_credit_succeed: 720,
      phase_credit_failed: 130,
    },
    {
      date: subDays(Date.now(), 5),
      workflow_execution_succeed: 60,
      workflow_execution_failed: 20,
      phase_execution_succeed: 240,
      phase_execution_failed: 28,
      phase_credit_succeed: 1010,
      phase_credit_failed: 65,
    },
    {
      date: subDays(Date.now(), 4),
      workflow_execution_succeed: 1510,
      workflow_execution_failed: 602,
      phase_execution_succeed: 95,
      phase_execution_failed: 80,
      phase_credit_succeed: 700,
      phase_credit_failed: 160,
    },
    {
      date: subDays(Date.now(), 3),
      workflow_execution_succeed: 1020,
      workflow_execution_failed: 42,
      phase_execution_succeed: 330,
      phase_execution_failed: 14,
      phase_credit_succeed: 1320,
      phase_credit_failed: 80,
    },
    {
      date: subDays(Date.now(), 2),
      workflow_execution_succeed: 493,
      workflow_execution_failed: 102,
      phase_execution_succeed: 11,
      phase_execution_failed: 499,
      phase_credit_succeed: 2034,
      phase_credit_failed: 199,
    },
    {
      date: startOfYesterday(),
      workflow_execution_succeed: 30,
      workflow_execution_failed: 80,
      phase_execution_succeed: 39,
      phase_execution_failed: 29,
      phase_credit_succeed: 1190,
      phase_credit_failed: 95,
    },
    {
      date: startOfToday(),
      workflow_execution_succeed: 30,
      workflow_execution_failed: 90,
      phase_execution_succeed: 305,
      phase_execution_failed: 20,
      phase_credit_succeed: 1180,
      phase_credit_failed: 100,
    },
  ];
};

export const folders: folderType[] = [
  {
    folderName: "Reports",
    folderColor: WORKFLOW_COLORS.indigo,
    folderPath: "r1e4t5s2", // Random ID
  },
  {
    folderName: "CRM Automation",
    folderColor: WORKFLOW_COLORS.blue,
    folderPath: "c5r3m1a2", // Random ID
  },
  {
    folderName: "Inventory",
    folderColor: WORKFLOW_COLORS.teal,
    folderPath: "i6n4v9t3r", // Random ID
  },
  {
    folderName: "Notifications",
    folderColor: WORKFLOW_COLORS.amber,
    folderPath: "n2o1t4s7", // Random ID
  },
  {
    folderName: "Marketing",
    folderColor: WORKFLOW_COLORS.slate,
    folderPath: "m9r8k5t1g", // Random ID
  },
  {
    folderName: "Email Campaigns",
    folderColor: WORKFLOW_COLORS.purple,
    folderPath: "e4m3c2p9s", // Random ID
  },
  {
    folderName: "Retention",
    folderColor: WORKFLOW_COLORS.red,
    folderPath: "r3e8t6n2", // Random ID
  },
  {
    folderName: "Social Media",
    folderColor: WORKFLOW_COLORS.yellow,
    folderPath: "s2m1d6a8", // Random ID
  },
  {
    folderName: "User Onboarding",
    folderColor: WORKFLOW_COLORS.green,
    folderPath: "u1o3b6n7", // Random ID
  },
  {
    folderName: "Backup & Security",
    folderColor: WORKFLOW_COLORS.slate,
    folderPath: "b7s3e8c9r", // Random ID
  },
  {
    folderName: "Finance",
    folderColor: WORKFLOW_COLORS.indigo,
    folderPath: "f9n1a5c2", // Random ID
  },
  {
    folderName: "Surveys",
    folderColor: WORKFLOW_COLORS.teal,
    folderPath: "s5r9e3y8s", // Random ID
  },
  {
    folderName: "DevOps",
    folderColor: WORKFLOW_COLORS.yellow,
    folderPath: "d7v3o2p9s", // Random ID
  },
];

export const fakeWorkflows: WorkflowCardType[] = [
  {
    title: "Daily Sales Report",
    creditCost: 10,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[0],
    isPinned: false,
    isActive: true,
    hasError: false,
    description:
      "Automated daily report that summarizes total sales and key metrics.",
    createdAt: new Date("2025-03-23"),
    updatedAt: new Date("2025-03-23"),
  },
  {
    title: "Lead Enrichment",
    creditCost: 15,
    triggerMode: "Webhook",
    state: "Published",
    folder: folders[1],
    isActive: true,
    hasError: false,
    description:
      "Enhance your CRM data with additional information about leads like company size, social profiles, and more.",
    createdAt: new Date("2025-01-10"),
    updatedAt: new Date("2025-01-10"),
  },
  {
    title: "Product Sync",
    creditCost: 8,
    triggerMode: "Manual",
    state: "Published",
    folder: folders[2],
    isPinned: false,
    isActive: true,
    hasError: false,
    description:
      "Keep your product catalog synced between your internal database and your e-commerce platforms.",
    createdAt: new Date("2024-12-18"),
    updatedAt: new Date("2025-01-07"),
  },
  {
    title: "New Order Alert",
    creditCost: 5,
    triggerMode: "Webhook",
    state: "Published",
    folder: folders[3],
    isPinned: true,
    isActive: true,
    hasError: false,
    description:
      "Instantly get notified when a new order is placed on your store.",
    createdAt: new Date("2025-01-02"),
    updatedAt: new Date("2025-01-14"),
  },
  {
    title: "Blog SEO Scan",
    creditCost: 12,
    triggerMode: "Manual",
    state: "Draft",
    folder: folders[4],
    isPinned: true,
    isActive: false,
    hasError: false,
    description:
      "Scan your blog content to identify SEO improvements such as keyword density, readability, and meta data suggestions.",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
  {
    title: "Weekly Email Digest",
    creditCost: 20,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[5],
    isPinned: true,
    isActive: true,
    hasError: true,
    description:
      "Send out a beautifully formatted weekly summary email to your subscribers with the top updates and content.",
    createdAt: new Date("2024-12-29"),
    updatedAt: new Date("2025-01-06"),
  },
  {
    title: "Abandoned Cart Reminder",
    creditCost: 18,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[6],
    isPinned: true,
    isActive: true,
    hasError: true,
    description:
      "Automatically remind users who left products in their cart to complete their purchase.",
    createdAt: new Date("2025-01-04"),
    updatedAt: new Date("2025-01-12"),
  },
  {
    title: "Instagram Auto Poster",
    creditCost: 25,
    triggerMode: "Manual",
    state: "Draft",
    folder: folders[7],
    isPinned: false,
    isActive: false,
    hasError: false,
    description:
      "Schedule and publish posts automatically to your Instagram account without manual intervention.",
    createdAt: new Date("2025-01-05"),
    updatedAt: new Date("2025-01-05"),
  },
  {
    title: "New User Welcome",
    creditCost: 7,
    triggerMode: "Webhook",
    state: "Published",
    folder: folders[8],
    isPinned: false,
    isActive: true,
    hasError: true,
    description:
      "Deliver a warm welcome to new users and guide them through your onboarding steps.",
    createdAt: new Date("2025-01-07"),
    updatedAt: new Date("2025-01-13"),
  },
  {
    title: "Backup to Google Drive",
    creditCost: 11,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[9],
    isPinned: true,
    isActive: true,
    hasError: false,
    description:
      "Automatically backup your critical files and data to a secure Google Drive folder every day.",
    createdAt: new Date("2024-12-22"),
    updatedAt: new Date("2025-01-02"),
  },
  {
    title: "Invoice Generator",
    creditCost: 9,
    triggerMode: "Manual",
    state: "Published",
    folder: folders[10],
    isPinned: false,
    isActive: true,
    hasError: false,
    description:
      "Generate professional-looking invoices on the fly and send them to your clients with just a few clicks.",
    createdAt: new Date("2024-12-28"),
    updatedAt: new Date("2025-01-11"),
  },
  {
    title: "Feedback Collector",
    creditCost: 6,
    triggerMode: "Webhook",
    state: "Draft",
    folder: folders[11],
    isPinned: true,
    isActive: false,
    hasError: true,
    description:
      "Capture customer feedback at key touchpoints and analyze sentiment for continuous improvement.",
    createdAt: new Date("2025-01-08"),
    updatedAt: new Date("2025-01-08"),
  },
  {
    title: "Server Health Monitor",
    creditCost: 14,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[12],
    isPinned: true,
    isActive: true,
    hasError: false,
    description:
      "Monitor your server uptime, performance metrics, and receive real-time alerts for anomalies.",
    createdAt: new Date("2025-01-03"),
    updatedAt: new Date("2025-01-14"),
  },
  {
    title: "Monthly Revenue Snapshot",
    creditCost: 13,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[0],
    isPinned: false,
    isActive: true,
    hasError: false,
    description:
      "Get a clean snapshot of your monthly revenue, broken down by product, region, and sales channel.",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-10"),
  },
  {
    title: "Product Performance Report",
    creditCost: 10,
    triggerMode: "Manual",
    state: "Published",
    folder: folders[0],
    isPinned: true,
    isActive: true,
    hasError: false,
    description:
      "Analyze how each product is performing over time in terms of revenue, engagement, and returns.",
    createdAt: new Date("2025-01-02"),
    updatedAt: new Date("2025-01-12"),
  },
  {
    title: "User Growth Report",
    creditCost: 12,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[0],
    isPinned: false,
    isActive: true,
    hasError: false,
    description:
      "Measure user acquisition trends and growth rate across different time periods.",
    createdAt: new Date("2025-01-03"),
    updatedAt: new Date("2025-01-13"),
  },
  {
    title: "Sales Team Performance",
    creditCost: 16,
    triggerMode: "Scheduled",
    state: "Draft",
    folder: folders[0],
    isPinned: false,
    isActive: false,
    hasError: false,
    description:
      "Compare the performance of your sales team members by deal value, close rate, and response time.",
    createdAt: new Date("2025-01-04"),
    updatedAt: new Date("2025-01-04"),
  },
  {
    title: "CRM Contact Sync",
    creditCost: 10,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[1],
    isPinned: true,
    isActive: true,
    hasError: true,
    description:
      "Ensure your CRM contact database stays updated with the latest changes from your other tools.",
    createdAt: new Date("2025-01-06"),
    updatedAt: new Date("2025-01-14"),
  },
  {
    title: "Duplicate Contact Cleaner",
    creditCost: 8,
    triggerMode: "Manual",
    state: "Draft",
    folder: folders[1],
    isPinned: false,
    isActive: false,
    hasError: false,
    description:
      "Identify and merge duplicate contact entries in your CRM system to maintain data cleanliness.",
    createdAt: new Date("2025-01-03"),
    updatedAt: new Date("2025-01-03"),
  },
  {
    title: "Lead Scoring Bot",
    creditCost: 18,
    triggerMode: "Webhook",
    state: "Published",
    folder: folders[1],
    isPinned: false,
    isActive: true,
    hasError: true,
    description:
      "Automatically score leads based on custom rules and behavior to prioritize follow-ups.",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-12"),
  },
  {
    title: "Customer Segmentation",
    creditCost: 14,
    triggerMode: "Manual",
    state: "Published",
    folder: folders[2],
    isPinned: false,
    isActive: true,
    hasError: false,
    description:
      "Segment your customers dynamically based on behavior, purchase history, and demographics.",
    createdAt: new Date("2025-01-04"),
    updatedAt: new Date("2025-01-09"),
  },
  {
    title: "Inventory Tracker",
    creditCost: 17,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[2],
    isPinned: true,
    isActive: true,
    hasError: true,
    description:
      "Track your product inventory levels across warehouses and receive alerts for low stock.",
    createdAt: new Date("2024-12-31"),
    updatedAt: new Date("2025-01-11"),
  },
  {
    title: "Order Status Notifier",
    creditCost: 6,
    triggerMode: "Webhook",
    state: "Published",
    folder: folders[3],
    isPinned: false,
    isActive: true,
    hasError: false,
    description:
      "Send real-time updates to customers about their order processing and delivery status.",
    createdAt: new Date("2025-01-05"),
    updatedAt: new Date("2025-01-07"),
  },
  {
    title: "New Review Alert",
    creditCost: 5,
    triggerMode: "Webhook",
    state: "Published",
    folder: folders[4],
    isPinned: true,
    isActive: true,
    hasError: false,
    description:
      "Get instantly notified when a new review is submitted on your product pages.",
    createdAt: new Date("2025-01-02"),
    updatedAt: new Date("2025-01-02"),
  },
  {
    title: "Affiliate Performance Report",
    creditCost: 13,
    triggerMode: "Manual",
    state: "Published",
    folder: folders[5],
    isPinned: false,
    isActive: true,
    hasError: false,
    description:
      "Track performance of each affiliate partner including clicks, conversions, and payouts.",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-12"),
  },
  {
    title: "Customer Support Analyzer",
    creditCost: 15,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[6],
    isPinned: true,
    isActive: true,
    hasError: true,
    description:
      "Analyze customer support tickets for common issues and agent performance.",
    createdAt: new Date("2024-12-30"),
    updatedAt: new Date("2025-01-10"),
  },
  {
    title: "Coupon Usage Tracker",
    creditCost: 7,
    triggerMode: "Manual",
    state: "Draft",
    folder: folders[7],
    isPinned: false,
    isActive: false,
    hasError: false,
    description:
      "Monitor how customers are using discount codes and identify top-performing promotions.",
    createdAt: new Date("2025-01-06"),
    updatedAt: new Date("2025-01-06"),
  },
  {
    title: "Churn Risk Detector",
    creditCost: 20,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[8],
    isPinned: true,
    isActive: true,
    hasError: false,
    description:
      "Predict which users are likely to churn based on behavior and engagement patterns.",
    createdAt: new Date("2025-01-07"),
    updatedAt: new Date("2025-01-14"),
  },
  {
    title: "Social Mentions Tracker",
    creditCost: 11,
    triggerMode: "Webhook",
    state: "Published",
    folder: folders[9],
    isPinned: false,
    isActive: true,
    hasError: true,
    description:
      "Track mentions of your brand across social media platforms in real time.",
    createdAt: new Date("2025-01-03"),
    updatedAt: new Date("2025-01-09"),
  },
  {
    title: "VIP Customer Monitor",
    creditCost: 9,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[10],
    isPinned: false,
    isActive: true,
    hasError: false,
    description:
      "Keep track of your most valuable customers and get alerts on their activity.",
    createdAt: new Date("2025-01-05"),
    updatedAt: new Date("2025-01-11"),
  },
  {
    title: "Refund Pattern Detector",
    creditCost: 12,
    triggerMode: "Scheduled",
    state: "Draft",
    folder: folders[11],
    isPinned: false,
    isActive: false,
    hasError: false,
    description:
      "Identify patterns in product returns and refunds to detect potential product issues.",
    createdAt: new Date("2025-01-04"),
    updatedAt: new Date("2025-01-04"),
  },
  {
    title: "Campaign ROI Calculator",
    creditCost: 13,
    triggerMode: "Manual",
    state: "Published",
    folder: folders[12],
    isPinned: true,
    isActive: true,
    hasError: false,
    description:
      "Calculate return on investment for each of your marketing campaigns using real-time data.",
    createdAt: new Date("2024-12-29"),
    updatedAt: new Date("2025-01-08"),
  },
  {
    title: "Data Sync Audit",
    creditCost: 8,
    triggerMode: "Manual",
    state: "Published",
    folder: folders[0],
    isPinned: false,
    isActive: true,
    hasError: false,
    description:
      "Run audits to detect data mismatches and sync failures between connected systems.",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-13"),
  },
  {
    title: "Form Submissions Collector",
    creditCost: 10,
    triggerMode: "Webhook",
    state: "Published",
    folder: folders[1],
    isPinned: true,
    isActive: true,
    hasError: false,
    description:
      "Collect and organize all form submissions from your site into a central dashboard.",
    createdAt: new Date("2025-01-02"),
    updatedAt: new Date("2025-01-10"),
  },
];

export const fakeImportedFiles: importedFile[] = [
  {
    name: "product_data.json",
    importedAt: new Date("2025-03-20T10:15:00Z"),
    fileCategory: "Workflow",
    fileType: "json",
    fileSizeInBytes: 20480,
    isSafe: true,
  },
  {
    name: "seo_guide.md",
    importedAt: new Date("2025-03-21T14:30:00Z"),
    fileCategory: "Knowledge Base",
    fileType: "markdown",
    fileSizeInBytes: 10240,
    isSafe: true,
  },
  {
    name: "customer_faq.txt",
    importedAt: new Date("2025-03-18T08:45:00Z"),
    fileCategory: "Knowledge Base",
    fileType: "txt",
    fileSizeInBytes: 5120,
    isSafe: true,
  },
  {
    name: "workflow_config.json",
    importedAt: new Date("2025-03-22T16:10:00Z"),
    fileCategory: "Workflow",
    fileType: "json",
    fileSizeInBytes: 30720,
    isSafe: true,
  },
  {
    name: "user_guide.html",
    importedAt: new Date("2025-03-19T11:20:00Z"),
    fileCategory: "Knowledge Base",
    fileType: "html",
    fileSizeInBytes: 25600,
    isSafe: true,
  },
  {
    name: "api_reference.md",
    importedAt: new Date("2025-03-17T09:00:00Z"),
    fileCategory: "Knowledge Base",
    fileType: "markdown",
    fileSizeInBytes: 153000260,
    isSafe: true,
  },
  {
    name: "site_backup.json",
    importedAt: new Date("2025-03-15T07:45:00Z"),
    fileCategory: "Workflow",
    fileType: "json",
    fileSizeInBytes: 51200,
    isSafe: true,
  },
  {
    name: "terms_of_service.txt",
    importedAt: new Date("2025-03-14T13:25:00Z"),
    fileCategory: "Knowledge Base",
    fileType: "txt",
    fileSizeInBytes: 8192,
    isSafe: true,
  },
  {
    name: "project_automation.json",
    importedAt: new Date("2025-03-16T18:55:00Z"),
    fileCategory: "Workflow",
    fileType: "json",
    fileSizeInBytes: 40960,
    isSafe: true,
  },
  {
    name: "business_strategy.md",
    importedAt: new Date("2025-03-23T20:30:00Z"),
    fileCategory: "Knowledge Base",
    fileType: "markdown",
    fileSizeInBytes: 12288,
    isSafe: true,
  },
  {
    name: "website_structure.html",
    importedAt: new Date("2025-03-20T15:40:00Z"),
    fileCategory: "Knowledge Base",
    fileType: "html",
    fileSizeInBytes: 34816,
    isSafe: true,
  },
  {
    name: "email_campaign_workflow.json",
    importedAt: new Date("2025-03-24T09:10:00Z"),
    fileCategory: "Workflow",
    fileType: "json",
    fileSizeInBytes: 28672,
    isSafe: true,
  },
  {
    name: "important_notes.txt",
    importedAt: new Date("2025-01-22T22:15:00Z"),
    fileCategory: "Knowledge Base",
    fileType: "txt",
    fileSizeInBytes: 4096,
    isSafe: true,
  },
];

export const fakeUsers: userProfile[] = [
  {
    name: "Alice Carter",
    avatar: generateAvatar("Alice Carter")?.toDataUri(),
  },
  {
    name: "Ben Johnson",
    avatar: generateAvatar("Ben Johnson")?.toDataUri(),
  },
  {
    name: "Charlie Evans",
    avatar: generateAvatar("Charlie Evans")?.toDataUri(),
  },
  {
    name: "Diana Smith",
    avatar: generateAvatar("Diana Smith")?.toDataUri(),
  },
  {
    name: "Ethan Brown",
    avatar: generateAvatar("Ethan Brown")?.toDataUri(),
  },
  {
    name: "Fiona Wilson",
    avatar: generateAvatar("Fiona Wilson")?.toDataUri(),
  },
  {
    name: "George White",
    avatar: generateAvatar("George White")?.toDataUri(),
  },
  {
    name: "Hannah Adams",
    avatar: generateAvatar("Hannah Adams")?.toDataUri(),
  },
  {
    name: "Isaac Green",
    avatar: generateAvatar("Isaac Green")?.toDataUri(),
  },
  {
    name: "Julia Roberts",
    avatar: generateAvatar("Julia Roberts")?.toDataUri(),
  },
];

export const fakeWorkflowTemplates: workflowTemplateType[] = [
  {
    owner: fakeUsers[0],
    title: "Lead Capture Automation",
    description:
      "Automatically collect and organize leads from multiple sources.",
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-15"),
    creditCost: 12,
    triggerMode: "Webhook",
    category: "Lead & Customer",
    downloads: 512,
    logoPath: generateWorkflowLogo(),
  },
  {
    owner: fakeUsers[1],
    title: "Abandoned Cart Recovery",
    description:
      "Send automated reminders to customers who left items in their cart.",
    createdAt: new Date("2025-02-25"),
    updatedAt: new Date("2025-03-10"),
    creditCost: 18,
    triggerMode: "Scheduled",
    category: "E-commerce & Sales",
    downloads: 842,
    logoPath: generateWorkflowLogo(),
  },
  {
    owner: fakeUsers[2],
    title: "Social Media Auto-Poster",
    description:
      "Schedule and post content across multiple social media platforms.",
    createdAt: new Date("2025-02-28"),
    updatedAt: new Date("2025-03-12"),
    creditCost: 15,
    triggerMode: "Manual",
    category: "Marketing & Social Media",
    downloads: 734,
    logoPath: generateWorkflowLogo(),
  },
  {
    owner: fakeUsers[3],
    title: "Sales Performance Report",
    description: "Generate weekly reports on sales team performance.",
    createdAt: new Date("2025-03-05"),
    updatedAt: new Date("2025-03-15"),
    creditCost: 10,
    triggerMode: "Scheduled",
    category: "Reporting & Analytics",
    downloads: 420,
    logoPath: generateWorkflowLogo(),
  },
  {
    owner: fakeUsers[4],
    title: "New Order Notifications",
    description: "Instant alerts when new orders are placed.",
    createdAt: new Date("2025-02-20"),
    updatedAt: new Date("2025-03-01"),
    creditCost: 8,
    triggerMode: "Webhook",
    category: "Notifications & Alerts",
    downloads: 1803238,
    logoPath: generateWorkflowLogo(),
  },
  {
    owner: fakeUsers[5],
    title: "Invoice Generator",
    description: "Automatically generate invoices for completed orders.",
    createdAt: new Date("2025-03-02"),
    updatedAt: new Date("2025-03-14"),
    creditCost: 14,
    triggerMode: "Scheduled",
    category: "Finance & Billing",
    downloads: 532,
    logoPath: generateWorkflowLogo(),
  },
  {
    owner: fakeUsers[6],
    title: "Meeting Reminder Workflow",
    description:
      "Send automated reminders for upcoming meetings and deadlines.",
    createdAt: new Date("2025-02-27"),
    updatedAt: new Date("2025-03-10"),
    creditCost: 9,
    triggerMode: "Manual",
    category: "Productivity & Workflows",
    downloads: 3929187,
    logoPath: generateWorkflowLogo(),
  },
  {
    owner: fakeUsers[7],
    title: "Web Scraping for Product Prices",
    description: "Extract and track competitor product prices automatically.",
    createdAt: new Date("2025-02-23"),
    updatedAt: new Date("2025-03-08"),
    creditCost: 20,
    triggerMode: "Scheduled",
    category: "Data Extraction & Scraping",
    downloads: 9780,
    logoPath: generateWorkflowLogo(),
  },
  {
    owner: fakeUsers[8],
    title: "Customer Feedback Collector",
    description: "Automate the collection of customer feedback post-purchase.",
    createdAt: new Date("2025-02-26"),
    updatedAt: new Date("2025-03-09"),
    creditCost: 11,
    triggerMode: "Webhook",
    category: "Lead & Customer",
    downloads: 618,
    logoPath: generateWorkflowLogo(),
  },
  {
    owner: fakeUsers[9],
    title: "Daily E-commerce Revenue Report",
    description: "Generate daily revenue summaries for your online store.",
    createdAt: new Date("2025-03-04"),
    updatedAt: new Date("2025-03-16"),
    creditCost: 16,
    triggerMode: "Scheduled",
    category: "E-commerce & Sales",
    downloads: 559039,
    logoPath: generateWorkflowLogo(),
  },
  {
    owner: fakeUsers[0],
    title: "Automated Twitter Engagement",
    description: "Reply, like, and retweet based on specific keywords.",
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-14"),
    creditCost: 12,
    triggerMode: "Manual",
    category: "Marketing & Social Media",
    downloads: 4002,
    logoPath: generateWorkflowLogo(),
  },
  {
    owner: fakeUsers[1],
    title: "SEO Audit Report",
    description: "Generate an SEO performance audit for any website.",
    createdAt: new Date("2025-02-25"),
    updatedAt: new Date("2025-03-11"),
    creditCost: 19,
    triggerMode: "Manual",
    category: "Reporting & Analytics",
    downloads: 27500,
    logoPath: generateWorkflowLogo(),
  },
  {
    owner: fakeUsers[2],
    title: "Slack Order Alerts",
    description: "Get instant Slack notifications for new orders.",
    createdAt: new Date("2025-02-28"),
    updatedAt: new Date("2025-03-09"),
    creditCost: 10,
    triggerMode: "Webhook",
    category: "Notifications & Alerts",
    downloads: 65402,

    logoPath: generateWorkflowLogo(),
  },
  {
    owner: fakeUsers[3],
    title: "Automated Payroll Processing",
    description: "Generate payroll reports and send payment reminders.",
    createdAt: new Date("2025-03-06"),
    updatedAt: new Date("2025-03-15"),
    creditCost: 15,
    triggerMode: "Scheduled",
    category: "Finance & Billing",
    downloads: 533,
    logoPath: generateWorkflowLogo(),
  },
  {
    owner: fakeUsers[4],
    title: "Task Completion Reminder",
    description: "Automatically remind users to complete pending tasks.",
    createdAt: new Date("2025-02-20"),
    updatedAt: new Date("2025-03-05"),
    creditCost: 8,
    triggerMode: "Scheduled",
    category: "Productivity & Workflows",
    downloads: 4901,
    logoPath: generateWorkflowLogo(),
  },
  {
    owner: fakeUsers[5],
    title: "Real-Time Stock Market Data Extraction",
    description: "Scrape stock market data for real-time insights.",
    createdAt: new Date("2025-03-02"),
    updatedAt: new Date("2025-03-10"),
    creditCost: 22,
    triggerMode: "Scheduled",
    category: "Data Extraction & Scraping",
    downloads: 1094,
    logoPath: generateWorkflowLogo(),
  },
  {
    owner: fakeUsers[6],
    title: "Email List Enrichment",
    description: "Enhance customer email lists with additional data points.",
    createdAt: new Date("2025-02-27"),
    updatedAt: new Date("2025-03-12"),
    creditCost: 13,
    triggerMode: "Webhook",
    category: "Lead & Customer",
    downloads: 30499110,
    logoPath: generateWorkflowLogo(),
  },
  {
    owner: fakeUsers[7],
    title: "E-commerce Abandonment Analytics",
    description: "Analyze cart abandonment trends and recovery rates.",
    createdAt: new Date("2025-02-23"),
    updatedAt: new Date("2025-03-08"),
    creditCost: 17,
    triggerMode: "Scheduled",
    category: "E-commerce & Sales",
    downloads: 70930,
    logoPath: generateWorkflowLogo(),
  },
  {
    owner: fakeUsers[8],
    title: "LinkedIn Auto Connection",
    description:
      "Automatically send connection requests based on search criteria.",
    createdAt: new Date("2025-02-26"),
    updatedAt: new Date("2025-03-07"),
    creditCost: 14,
    triggerMode: "Manual",
    category: "Marketing & Social Media",
    downloads: 611,
    logoPath: generateWorkflowLogo(),
  },
];

export const fakeKnowledgeBases: knowledgeBase[] = [
  {
    name: "OpsSync Knowledge Hub",
    id: "OpsSync Knowledge Hub",
  },
  {
    name: "FlowMaster Docs",
    id: "FlowMaster Docs",
  },
  {
    name: "ProcessIQ Playbook",
    id: "ProcessIQ Playbook",
  },
  {
    name: "Streamline SOPs",
    id: "Streamline SOPs",
  },
  {
    name: "TaskBridge Automation Guide",
    id: "TaskBridge Automation Guide",
  },
  {
    name: "SyncPoint Documentation",
    id: "SyncPoint Documentation",
  },
  {
    name: "ClearPath AI Workflows",
    id: "ClearPath AI Workflows",
  },
  {
    name: "OptimizeOps Manual",
    id: "OptimizeOps Manual",
  },
  {
    name: "WorkFusion Knowledge Base",
    id: "WorkFusion Knowledge Base",
  },
  {
    name: "TaskFlow Internal Docs",
    id: "TaskFlow Internal Docs",
  },
];

export const fakeConversation1: ChatReply[] = [
  {
    from: "user",
    content:
      "Hi, I need help building an automation workflow for handling e-commerce orders. Can you suggest something?",
    createdAt: new Date("2025-03-30T10:00:00"),
  },
  {
    from: "model",
    content: (
      <div className="min-w-full">
        Sure! For e-commerce orders, a basic workflow could look like this:
        <br />
        1. New Order Received <br />
        2. Send Confirmation Email <br />
        3. Process Payment <br />
        4. Notify Warehouse <br />
        5. Update Inventory 6. Ship Order <br />
        7. Send Delivery <br />
        Confirmation. Does this look good?
        <br />
        <br />
        <b>Here a preview:</b>
        <WorkflowTemplatePreview key={"abc123"} containerHeight={"50vh"} />
      </div>
    ),
    createdAt: new Date("2025-03-30T10:02:00"),
  },
  {
    from: "user",
    content:
      "Hmm, I like it, but I want to add a step before sending the confirmation email to verify the order. Maybe a quick validation of payment info first?",
    createdAt: new Date("2025-03-30T10:05:00"),
  },
  {
    from: "model",
    content:
      "Got it! Here's an updated workflow: 1. New Order Received 2. Verify Payment Information 3. Send Confirmation Email 4. Process Payment 5. Notify Warehouse 6. Update Inventory 7. Ship Order 8. Send Delivery Confirmation.",
    createdAt: new Date("2025-03-30T10:07:00"),
  },
  {
    from: "user",
    content:
      "That works, but now I realize the warehouse notification should come after payment processing, just to be safe.",
    createdAt: new Date("2025-03-30T10:10:00"),
  },
  {
    from: "model",
    content:
      "Sure, here's the updated workflow: 1. New Order Received 2. Verify Payment Information 3. Send Confirmation Email 4. Process Payment 5. Notify Warehouse 6. Update Inventory 7. Ship Order 8. Send Delivery Confirmation.",
    createdAt: new Date("2025-03-30T10:12:00"),
  },
  {
    from: "user",
    content:
      "Actually, I want to add an email reminder to the customer before shipping. Can you add that in?",
    createdAt: new Date("2025-03-30T10:15:00"),
  },
  {
    from: "model",
    content: (
      <div>
        Of course! Here’s the revised workflow with the email reminder added:
        <br />
        1.New Order Received 2. Verify Payment Information 3. Send Confirmation
        Email 4. Process Payment 5. Notify Warehouse 6. Update Inventory 7. Send
        Shipping Reminder Email 8. Ship Order 9. Send Delivery Confirmation.
        <br />
        <br />
        You can try it below:
        <WorkflowTemplatePreview
          key={"efg456"}
          containerWidth={"100%"}
          containerHeight={"70vh"}
        />
      </div>
    ),

    createdAt: new Date("2025-03-30T10:17:00"),
  },
  {
    from: "user",
    content:
      "Perfect! Now I’m thinking about adding a step where the system checks stock levels before notifying the warehouse. Can you insert that?",
    createdAt: new Date("2025-03-30T10:20:00"),
  },
  {
    from: "model",
    content: (
      <div>
        Great idea! Here’s the updated workflow: <br />
        1. New Order Received <br />
        2. Verify Payment Information <br />
        3. Send Confirmation Email <br />
        4. Process Payment <br />
        5. Check Stock Levels <br />
        6. Notify Warehouse <br />
        7. Update Inventory <br />
        8. Send Shipping Reminder Email <br />
        9. Ship Order <br />
        10. Send Delivery Confirmation.
      </div>
    ),

    createdAt: new Date("2025-03-30T10:22:00"),
  },
  {
    from: "user",
    content: "Thanks!",
    createdAt: new Date("2025-03-30T10:22:01"),
  },
  {
    from: "model",
    content: "You're welcome!",
    createdAt: new Date("2025-03-30T10:22:02"),
  },
];

export const allChats: ChatItemType[] = [
  {
    chatId: "3iv7htghbp2futlhb4k",
    chatTitle: "Automate lead capture for my website",
    chatHistory: fakeConversation1,
    lastMessageDate: new Date("2025-02-03T14:25:36"),
  },
  {
    chatId: "or5z8xt2kp3v8hzgyzn",
    chatTitle: "Generate a workflow for abandoned cart recovery",
    chatHistory: fakeConversation1,
    lastMessageDate: new Date("2025-02-07T09:18:52"),
  },
  {
    chatId: "1f78k3rd5j7qxt8zmn2",
    chatTitle: "Set up an AI-powered email follow-up sequence",
    chatHistory: fakeConversation1,
    lastMessageDate: new Date("2025-02-12T21:45:19"),
  },
  {
    chatId: "z90jv7syqg6bptghc5b",
    chatTitle: "Extract and organize data from PDFs automatically",
    chatHistory: fakeConversation1,
    lastMessageDate: new Date("2025-02-16T08:30:42"),
  },
  {
    chatId: "5ct53pvg85yqk4u8r9e",
    chatTitle: "Create a workflow for daily sales reporting",
    chatHistory: fakeConversation1,
    lastMessageDate: new Date("2025-02-22T17:12:08"),
  },
  {
    chatId: "9s8l4bybf5awjv7htkg",
    chatTitle: "Schedule automated social media posts",
    chatHistory: fakeConversation1,
    lastMessageDate: new Date("2025-02-25T13:55:27"),
  },
  {
    chatId: "z4b81qdo3j9iuv5fphx",
    chatTitle: "Scrape product prices from competitor websites",
    chatHistory: fakeConversation1,
    lastMessageDate: new Date("2025-03-01T10:05:33"),
  },
  {
    chatId: "j79w3z82pvo6b9tuv2f",
    chatTitle: "Trigger Slack notifications for new customer sign-ups",
    chatHistory: fakeConversation1,
    lastMessageDate: new Date("2025-03-05T22:49:11"),
  },
  {
    chatId: "r5ynw7xv9ti6b4zx2zj",
    chatTitle: "Generate invoices automatically after payments",
    chatHistory: fakeConversation1,
    lastMessageDate: new Date("2025-03-08T16:37:59"),
  },
  {
    chatId: "kfg7i5tz9b8f3xuywmp",
    chatTitle: "Build an AI-based chatbot for customer inquiries",
    chatHistory: fakeConversation1,
    lastMessageDate: new Date("2025-03-11T07:23:44"),
  },
  {
    chatId: "pg2mv9w58t4qlub7rjw",
    chatTitle: "Sync CRM contacts with my email list",
    chatHistory: fakeConversation1,
    lastMessageDate: new Date("2025-03-14T19:28:20"),
  },
  {
    chatId: "fu4y9z3krn6vmt9iwkh",
    chatTitle: "Send personalized discounts to returning customers",
    chatHistory: fakeConversation1,
    lastMessageDate: new Date("2025-03-17T12:09:14"),
  },
  {
    chatId: "ixh7mpt6q0v3d5yjqw9",
    chatTitle: "Automate reminders for upcoming meetings",
    chatHistory: fakeConversation1,
    lastMessageDate: new Date("2025-03-19T05:33:48"),
  },
  {
    chatId: "g58q9w5j7svhyn2kz3e",
    chatTitle: "Schedule database backups at midnight daily",
    chatHistory: fakeConversation1,
    lastMessageDate: new Date("2025-03-21T20:40:31"),
  },
  {
    chatId: "ubh3t0jz7qw9kx2frtp",
    chatTitle: "Monitor and alert when website downtime is detected",
    chatHistory: fakeConversation1,
    lastMessageDate: new Date("2025-03-24T11:15:22"),
  },
  {
    chatId: "ts2f9myo8bp5g6zdqkw",
    chatTitle: "Fetch and analyze sentiment from customer reviews",
    chatHistory: fakeConversation1,
    lastMessageDate: new Date("2025-03-26T18:59:37"),
  },
  {
    chatId: "3vwq7b8jt9l2p40z5dn",
    chatTitle: "Automate tagging and sorting of incoming emails",
    chatHistory: fakeConversation1,
    lastMessageDate: new Date("2025-03-28T14:42:03"),
  },
  {
    chatId: "o0rskj7t9z83b1kpmfu",
    chatTitle: "Trigger push notifications for low stock alerts",
    chatHistory: fakeConversation1,
    lastMessageDate: new Date("2025-03-29T09:56:50"),
  },
  {
    chatId: "lhk2xmv9h2p5zwg3t1s",
    chatTitle: "Automatically format and clean scraped data",
    chatHistory: fakeConversation1,
    lastMessageDate: new Date("2025-03-30T22:05:16"),
  },
  {
    chatId: "f60ptv7yb3g9z2dq1vs",
    chatTitle: "Schedule auto-generated SEO reports every week",
    chatHistory: fakeConversation1,
    lastMessageDate: new Date("2025-03-30T22:20:27"),
  },
];

export const fakeRuns: RunItemType[] = [
  {
    runId: "3Jsqz1e085Ssaw1e6qwwJ29Slsd",
    startedAt: new Date("2025-03-30T10:30:07"),
    creditConsumed: 13,
    status: "paused",
    isInternalTest: true,
  },
  {
    runId: "KDnahlunmi2e92ssa5sieflke",
    startedAt: new Date("2025-02-30T22:20:39"),
    creditConsumed: 3,
    status: "running",
    isInternalTest: false,
  },
  {
    runId: "vsepko92rjuw2xr2q885z",
    startedAt: new Date("2025-03-13T21:20:41"),
    creditConsumed: 39,
    status: "failed",
    isInternalTest: false,
  },
  {
    runId: "bh65nhlunmi2esa5sin3s",
    startedAt: new Date("2025-03-20T19:21:44"),
    creditConsumed: 102,
    status: "success",
    isInternalTest: true,
  },
  {
    runId: "c1wot88orhwnv8deiqgk0",
    startedAt: new Date("2025-03-30T10:30:02"),
    creditConsumed: 6,
    status: "paused",
    isInternalTest: true,
  },
  {
    runId: "torwe0nscds6552dti1wj",
    startedAt: new Date("2025-02-18T09:20:18"),
    creditConsumed: 37,
    status: "running",
    isInternalTest: false,
  },
  {
    runId: "y2l6z1e085dw1e6qww8ur",
    startedAt: new Date("2025-03-14T10:30:09"),
    creditConsumed: 12,
    status: "success",
    isInternalTest: false,
  },
  {
    runId: "ncy7entfu7m17q6wu4b92",
    startedAt: new Date("2025-03-20T03:28:11"),
    creditConsumed: 10,
    status: "failed",
    isInternalTest: true,
  },
  {
    runId: "hb9ok1q0n1zd1pv7x973y",
    startedAt: new Date("2025-04-01T07:28:04"),
    creditConsumed: 9,
    status: "failed",
    isInternalTest: true,
  },
  {
    runId: "40sbc1tlojati7mlnvzge",
    startedAt: new Date("2025-04-01T06:29:01"),
    creditConsumed: 56,
    status: "success",
    isInternalTest: true,
  },
];

export const fakeDataInputs: PhaseInput[] = [
  { label: "URL", type: "string", value: "https://example.com/data" },
  { label: "Max Entries", type: "number", value: 100 },
  { label: "Enable Pagination", type: "boolean", value: true },
  { label: "Headers", type: "JSON", value: { Authorization: "Bearer token" } },
  { label: "Timeout", type: "number", value: 5000 },
];

export const fakeDataOutputs: PhaseOutput[] = [
  { label: "Extracted Items", type: "number", value: 87 },
  {
    label: "Data Sample",
    type: "JSON",
    value: fakeBigJSON,
  },
  { label: "Errors Encountered", type: "null", value: null },
];

export const fakePhaseLog: PhaseLog[] = [
  {
    time: new Date("2025-03-30T10:30:17"),
    level: "Info",
    message: "Workflow execution started.",
  },
  {
    time: new Date("2025-03-30T10:30:18"),
    level: "Info",
    message: "Fetching data from source.",
  },
  {
    time: new Date("2025-03-30T10:30:19"),
    level: "Alert",
    message: "Pagination limit reached.",
  },
  {
    time: new Date("2025-03-30T10:30:20"),
    level: "Info",
    message: "Processing extracted data.",
  },
  {
    time: new Date("2025-03-30T10:30:21"),
    level: "Failed",
    message: "Error parsing JSON response.",
  },
  {
    time: new Date("2025-03-30T10:30:22"),
    level: "Info",
    message: "Retrying failed request.",
  },
  {
    time: new Date("2025-03-30T10:30:23"),
    level: "Failed",
    message: "Timeout reached while fetching data.",
  },
  {
    time: new Date("2025-03-30T10:30:24"),
    level: "Alert",
    message: "Partial data extracted due to errors. Click to see more",
  },
  {
    time: new Date("2025-03-30T10:30:25"),
    level: "Info",
    message: "Logging workflow results.",
  },
  {
    time: new Date("2025-03-30T10:30:26"),
    level: "Failed",
    message: "Workflow terminated due to critical error.",
  },
];

export const fakePhases: PhaseItemType[] = [
  {
    startedAt: new Date("2025-03-30T10:30:07"),
    durationMs: 1003,
    title: "Launch Browser",
    creditConsumed: 4,
    status: "paused",
    dataInputs: fakeDataInputs,
    dataOutputs: fakeDataOutputs,
    logs: fakePhaseLog,
  },
  {
    startedAt: new Date("2025-03-30T10:30:10"),
    durationMs: 2050,
    title: "Navigate to URL",
    creditConsumed: 3,
    status: "success",

    dataInputs: fakeDataInputs,
    dataOutputs: fakeDataOutputs,
    logs: fakePhaseLog,
  },
  {
    startedAt: new Date("2025-03-30T10:30:13"),
    durationMs: 1578,
    title: "Wait for Page Load",
    creditConsumed: 2,
    status: "success",

    dataInputs: fakeDataInputs,
    dataOutputs: fakeDataOutputs,
    logs: fakePhaseLog,
  },
  {
    startedAt: new Date("2025-03-30T10:30:16"),
    durationMs: 1200,
    title: "Extract Data",
    creditConsumed: 5,
    status: "failed",

    dataInputs: fakeDataInputs,
    dataOutputs: fakeDataOutputs,
    logs: fakePhaseLog,
  },
  {
    startedAt: new Date("2025-03-30T10:30:20"),
    durationMs: 980,
    title: "Validate Extracted Data",
    creditConsumed: 3,
    status: "success",

    dataInputs: fakeDataInputs,
    dataOutputs: fakeDataOutputs,
    logs: fakePhaseLog,
  },
  {
    startedAt: new Date("2025-03-30T10:30:22"),
    durationMs: 2500,
    title: "Format Data",
    creditConsumed: 2,
    status: "running",

    dataInputs: fakeDataInputs,
    dataOutputs: fakeDataOutputs,
    logs: fakePhaseLog,
  },
  {
    startedAt: new Date("2025-03-30T10:30:26"),
    durationMs: 3150,
    title: "Store Data in Database",
    creditConsumed: 6,
    status: "success",

    dataInputs: fakeDataInputs,
    dataOutputs: fakeDataOutputs,
    logs: fakePhaseLog,
  },
  {
    startedAt: new Date("2025-03-30T10:30:30"),
    durationMs: 1750,
    title: "Trigger API Request",
    creditConsumed: 4,
    status: "running",

    dataInputs: fakeDataInputs,
    dataOutputs: fakeDataOutputs,
    logs: fakePhaseLog,
  },
  {
    startedAt: new Date("2025-03-30T10:30:33"),
    durationMs: 2450,
    title: "Handle API Response",
    creditConsumed: 3,
    status: "success",

    dataInputs: fakeDataInputs,
    dataOutputs: fakeDataOutputs,
    logs: fakePhaseLog,
  },
  {
    startedAt: new Date("2025-03-30T10:30:36"),
    durationMs: 1850,
    title: "Check for Errors",
    creditConsumed: 2,
    status: "success",

    dataInputs: fakeDataInputs,
    dataOutputs: fakeDataOutputs,
    logs: fakePhaseLog,
  },
  {
    startedAt: new Date("2025-03-30T10:30:39"),
    durationMs: 950,
    title: "Send Notification",
    creditConsumed: 1,
    status: "success",

    dataInputs: fakeDataInputs,
    dataOutputs: fakeDataOutputs,
    logs: fakePhaseLog,
  },
  {
    startedAt: new Date("2025-03-30T10:30:41"),
    durationMs: 2750,
    title: "Generate Report",
    creditConsumed: 4,
    status: "success",

    dataInputs: fakeDataInputs,
    dataOutputs: fakeDataOutputs,
    logs: fakePhaseLog,
  },
  {
    startedAt: new Date("2025-03-30T10:30:45"),
    durationMs: 800,
    title: "Close Browser",
    creditConsumed: 1,
    status: "success",
    dataInputs: fakeDataInputs,
    dataOutputs: fakeDataOutputs,
    logs: fakePhaseLog,
  },
  {
    startedAt: new Date("2025-03-30T10:30:47"),
    durationMs: 1300,
    title: "Archive Workflow Logs",
    creditConsumed: 2,
    status: "success",
    dataInputs: fakeDataInputs,
    dataOutputs: fakeDataOutputs,
    logs: fakePhaseLog,
  },
];
