import { InboxItemType } from "@/app/(protected)/_inbox/inbox";
import { trashItemType } from "@/app/(protected)/_trash/trash";
import { statsDataItemType } from "@/app/(protected)/dashboard/_components/stats_charts";
import { WorkflowCardType } from "@/app/(protected)/workflows/_components/workflow_card";
import { subDays, startOfYesterday, startOfToday } from "date-fns";
import { WORKFLOW_COLORS } from "./colors";
import { folderType } from "@/app/(protected)/workflows/layout";
import { importedFile } from "@/app/(protected)/_settings/import/import_settings";

export const userEmail = "kabundele@gmail.com";

export const trashItems: trashItemType[] = [
  {
    title: "Email Automation",
    subTitle: "Old marketing campaign flow",
  },
  {
    title: "Client Support - Sarah",
    subTitle: "Archived support conversation",
  },
  { title: "Lead Nurturing", subTitle: "Outdated CRM flow" },
  {
    title: "Project Update - John",
    subTitle: "Weekly project discussion",
  },
  {
    title: "Invoice Reminder",
    subTitle: "Automation for late payments",
  },
  {
    title: "Team Brainstorm",
    subTitle: "Old group chat for Q1 ideas",
  },
  {
    title: "Survey Follow-Up",
    subTitle: "Inactive customer feedback sequence",
  },
  {
    title: "Vendor Inquiry",
    subTitle: "Chat with supplier regarding materials",
  },
  {
    title: "Product Launch Flow",
    subTitle: "Retired campaign for V2",
  },
  {
    title: "Internal QA Discussion",
    subTitle: "Testing feedback conversation",
  },
  {
    title: "Appointment Booking",
    subTitle: "Deprecated calendar sync flow",
  },
  {
    title: "Customer Onboarding - Alex",
    subTitle: "Welcome chat from onboarding",
  },
  {
    title: "Blog Promotion",
    subTitle: "Old social media automation",
  },
  {
    title: "Design Review Chat",
    subTitle: "Archived UI feedback conversation",
  },
  {
    title: "Abandoned Cart Reminder",
    subTitle: "Legacy eCommerce automation",
  },
];

export const inboxItems: InboxItemType[] = [
  {
    date: new Date("2025-03-17T22:00:15"),
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    subjectLine: "Yesss Sarah shared you access to a workflow",
    content: [
      "You have been granted access to a new workflow. Click accept to validate your access",
      "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      "Eos numquam dolorem molestias architecto repudiandae aliquam corporis ipsum temporibus nesciunt minima?",
    ],
    actions: ["view", "accept", "refuse"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-03-16T14:20:30"),
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    subjectLine: "Gogo workflow execution failed: Inventory Management",
    content: [
      "The workflow execution id:40dek9JKsos2sPA failed due to this error: not enough credits.",
    ],
    actions: ["view", "retry"],
    isRead: true,
    isArchived: true,
  },
  {
    date: new Date("2025-03-15T10:15:10"),
    avatar: "https://randomuser.me/api/portraits/women/5.jpg",
    subjectLine: "Sarah shared you access to a workflow",
    content: [
      "A new workflow has been shared with you. Check it out!. ",
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos numquam dolorem molestias architecto repudiandae aliquam corporis ipsum temporibus nesciunt minima? Optio recusandae voluptatibus necessitatibus impedit minus magni quidem, vel dolores. consectetur adipisicing elit.",
      "Eos numquam dolorem molestias architecto repudiandae aliquam corporis ipsum temporibus",
      "nesciunt minima? Optio recusandae voluptatibus necessitatibus impedit minus magni quidem, vel dolores",
    ],
    actions: ["view", "accept", "refuse"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-03-17T20:10:15"),
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
    subjectLine: "Your workflow execution failed: Order Processing",
    content: ["Execution failed due to network errors. Please try again."],
    actions: ["view", "retry"],
    isRead: true,
    isArchived: false,
  },
  {
    date: new Date("2025-03-13T12:10:50"),
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
    subjectLine: "Worflow access accepted",
    content: [
      "You have confirmed your access to the workflow shared by Sarah",
      "Optio recusandae voluptatibus necessitatibus impedit minus magni quidem, vel dolores. consectetur adipisicing elit.",
    ],
    actions: ["view"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-03-12T16:00:40"),
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    subjectLine: "Your workflow execution failed: Payment Gateway",
    content: ["The payment gateway workflow failed. Please check the logs."],
    actions: ["view", "retry"],
    isRead: true,
    isArchived: true,
  },
  {
    date: new Date("2025-03-11T09:30:25"),
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
    subjectLine: "Your workflow execution failed: User Registration",
    content: ["A failure occurred during user registration. Please review."],
    actions: ["view", "retry"],
    isRead: false,
    isArchived: true,
  },
  {
    date: new Date("2025-03-10T17:45:10"),
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
    subjectLine: "Michael shared you access to a workflow",
    content: ["You've been granted access to a workflow related to orders."],
    actions: ["view"],
    isRead: true,
    isArchived: false,
  },
  {
    date: new Date("2025-03-09T11:20:55"),
    avatar: "https://randomuser.me/api/portraits/women/9.jpg",
    subjectLine: "Your workflow execution failed: Inventory Update",
    content: ["The workflow failed due to an error with the database."],
    actions: ["view", "retry"],
    isRead: true,
    isArchived: true,
  },
  {
    date: new Date("2025-03-08T15:50:40"),
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
    subjectLine: "Frank shared you access to a workflow",
    content: ["New workflow has been shared. Please review and proceed."],
    actions: ["view", "accept", "refuse"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-03-07T18:25:10"),
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    subjectLine: "Your workflow execution failed: Report Generation",
    content: ["Failure detected in report generation. Kindly investigate."],
    actions: ["view", "retry"],
    isRead: true,
    isArchived: false,
  },
  {
    date: new Date("2025-03-06T13:40:50"),
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    subjectLine: "Your workflow execution failed: Data Sync",
    content: [
      "The sync operation failed due to data inconsistency.",
      "Optio recusandae voluptatibus necessitatibus impedit minus magni quidem, vel dolores. consectetur adipisicing elit.",
    ],
    actions: ["view", "retry"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-03-04T14:10:30"),
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
    subjectLine: "Your workflow execution succeed: Notification System",
    content: [
      "The notification system workflow has been successfully executed.",
    ],
    actions: [],
    isRead: false,
    isArchived: true,
  },
  {
    date: new Date("2025-03-11T09:45:00"),
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
    subjectLine: "New update on your shared workflow",
    content: ["Workflow ‘User Onboarding’ has received new changes."],
    actions: ["view"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-03-10T11:15:30"),
    avatar: "https://randomuser.me/api/portraits/women/11.jpg",
    subjectLine: "Workflow execution succeeded: Billing Automation",
    content: ["The billing automation executed successfully."],
    actions: ["view"],
    isRead: true,
    isArchived: false,
  },
  {
    date: new Date("2025-03-14T08:05:12"),
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
    subjectLine: "Workflow execution failed: Lead Generation",
    content: ["Credits limit exceeded. Retry after upgrading your plan."],
    actions: ["view", "retry"],
    isRead: false,
    isArchived: true,
  },
  {
    date: new Date("2025-03-09T17:20:45"),
    avatar: "https://randomuser.me/api/portraits/women/10.jpg",
    subjectLine: "Alex granted you access to Workflow Hub",
    content: ["You’ve been added to Workflow Hub. Accept to get started."],
    actions: ["view", "accept", "refuse"],
    isRead: true,
    isArchived: false,
  },
  {
    date: new Date("2025-03-08T19:55:21"),
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
    subjectLine: "Reminder: Pending workflow access request",
    content: ["You have not yet accepted the shared workflow access."],
    actions: ["view", "accept", "refuse"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-03-06T13:35:10"),
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    subjectLine: "Workflow execution failed: Data Sync",
    content: ["Failure in syncing external data sources."],
    actions: ["view", "retry"],
    isRead: false,
    isArchived: true,
  },
  {
    date: new Date("2025-03-05T10:25:00"),
    avatar: "https://randomuser.me/api/portraits/men/10.jpg",
    subjectLine: "System update: Improved workflow builder",
    content: [
      "New drag and drop features added.",
      "You can now organize steps visually.",
    ],
    actions: ["view"],
    isRead: true,
    isArchived: false,
  },
  {
    date: new Date("2025-03-04T22:05:00"),
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
    subjectLine: "You’ve been mentioned in a workflow comment",
    content: ["@You Please review the last execution details."],
    actions: ["view"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-03-03T09:00:00"),
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
    subjectLine: "Reminder: Archive unused workflows",
    content: ["You have 5 workflows inactive for 30+ days."],
    actions: ["view"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-03-02T14:40:00"),
    avatar: "https://randomuser.me/api/portraits/women/1.jpg",
    subjectLine: "Team workflow shared with you: Analytics Reports",
    content: [
      "You’ve been granted access by Daniel.",
      "View and collaborate on this analytics workflow.",
    ],
    actions: ["view", "accept", "refuse"],
    isRead: true,
    isArchived: true,
  },
  {
    date: new Date("2025-03-01T15:45:50"),
    avatar: "https://randomuser.me/api/portraits/men/8.jpg",
    subjectLine: "Workflow execution alert: Email Campaign",
    content: ["Execution took longer than expected."],
    actions: ["view", "retry"],
    isRead: true,
    isArchived: false,
  },
  {
    date: new Date("2025-02-29T18:30:00"),
    avatar: "https://randomuser.me/api/portraits/women/7.jpg",
    subjectLine: "You were removed from a shared workflow",
    content: ["Your access to workflow ‘Daily Report’ was revoked."],
    actions: ["view"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-02-28T21:15:10"),
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
    subjectLine: "Workflow archive confirmation",
    content: ["You successfully archived ‘Monthly Sync’ workflow."],
    actions: ["view"],
    isRead: true,
    isArchived: true,
  },
  {
    date: new Date("2025-02-27T11:50:00"),
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    subjectLine: "Workflow update: Trigger conditions",
    content: ["New trigger conditions are now available for your workflows."],
    actions: ["view"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-02-26T08:25:10"),
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    subjectLine: "Security alert: Workflow permissions changed",
    content: ["Permissions for ‘HR Onboarding’ were modified recently."],
    actions: ["view"],
    isRead: false,
    isArchived: true,
  },
  {
    date: new Date("2025-02-25T17:00:45"),
    avatar: "https://randomuser.me/api/portraits/women/9.jpg",
    subjectLine: "Reminder: Accept shared workflow",
    content: ["‘Feedback Loop’ is still waiting for your confirmation."],
    actions: ["view", "accept", "refuse"],
    isRead: true,
    isArchived: false,
  },
  {
    date: new Date("2025-02-24T13:13:30"),
    avatar: "https://randomuser.me/api/portraits/men/12.jpg",
    subjectLine: "Execution failed: CRM Integration",
    content: ["API key invalid. Please verify your CRM integration."],
    actions: ["view", "retry"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-02-23T10:33:00"),
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
    subjectLine: "yoyo",
    content: [
      "Workflow completion: Event Automation. Your event automation completed successfully.",
    ],
    actions: ["view"],
    isRead: true,
    isArchived: true,
  },
  {
    date: new Date("2025-02-22T16:10:00"),
    avatar: "https://randomuser.me/api/portraits/men/13.jpg",
    subjectLine: "Alert: Low success rate in workflow",
    content: [
      "Only 3 of 10 executions succeeded.",
      "Consider reviewing your logic.",
    ],
    actions: ["view", "retry"],
    isRead: false,
    isArchived: false,
  },
  {
    date: new Date("2025-02-21T12:12:12"),
    avatar: "https://randomuser.me/api/portraits/women/14.jpg",
    subjectLine: "You've been invited to join a workflow: Growth Engine",
    content: [
      "David invited you to participate in a new growth automation workflow.",
    ],
    actions: ["view", "accept", "refuse"],
    isRead: false,
    isArchived: false,
  },
];

export const statsData: statsDataItemType = {
  "Order Fulfillment Workflow": [
    {
      date: new Date("2025-03-24"),
      workflow_execution_succeed: 10,
      workflow_execution_failed: 50,
      phase_execution_succeed: 250,
      phase_execution_failed: 30,
      phase_credit_succeed: 900,
      phase_credit_failed: 120,
    },
    {
      date: new Date("2025-03-23"),
      workflow_execution_succeed: 30,
      workflow_execution_failed: 45,
      phase_execution_succeed: 240,
      phase_execution_failed: 35,
      phase_credit_succeed: 950,
      phase_credit_failed: 100,
    },
    {
      date: new Date("2025-03-22"),
      workflow_execution_succeed: 50,
      workflow_execution_failed: 40,
      phase_execution_succeed: 230,
      phase_execution_failed: 40,
      phase_credit_succeed: 1000,
      phase_credit_failed: 80,
    },
    {
      date: new Date("2025-03-21"),
      workflow_execution_succeed: 70,
      workflow_execution_failed: 35,
      phase_execution_succeed: 220,
      phase_execution_failed: 45,
      phase_credit_succeed: 1100,
      phase_credit_failed: 60,
    },
    {
      date: new Date("2025-03-20"),
      workflow_execution_succeed: 40,
      workflow_execution_failed: 30,
      phase_execution_succeed: 210,
      phase_execution_failed: 50,
      phase_credit_succeed: 1200,
      phase_credit_failed: 70,
    },
    {
      date: new Date("2025-03-19"),
      workflow_execution_succeed: 60,
      workflow_execution_failed: 25,
      phase_execution_succeed: 200,
      phase_execution_failed: 55,
      phase_credit_succeed: 1300,
      phase_credit_failed: 60,
    },
    {
      date: new Date("2025-03-18"),
      workflow_execution_succeed: 90,
      workflow_execution_failed: 20,
      phase_execution_succeed: 190,
      phase_execution_failed: 60,
      phase_credit_succeed: 1400,
      phase_credit_failed: 50,
    },
    {
      date: new Date("2025-03-17"),
      workflow_execution_succeed: 50,
      workflow_execution_failed: 25,
      phase_execution_succeed: 180,
      phase_execution_failed: 65,
      phase_credit_succeed: 1300,
      phase_credit_failed: 55,
    },
    {
      date: new Date("2025-03-16"),
      workflow_execution_succeed: 80,
      workflow_execution_failed: 15,
      phase_execution_succeed: 170,
      phase_execution_failed: 70,
      phase_credit_succeed: 1200,
      phase_credit_failed: 65,
    },
    {
      date: new Date("2025-03-15"),
      workflow_execution_succeed: 60,
      workflow_execution_failed: 20,
      phase_execution_succeed: 160,
      phase_execution_failed: 75,
      phase_credit_succeed: 1100,
      phase_credit_failed: 75,
    },
    {
      date: new Date("2025-03-14"),
      workflow_execution_succeed: 70,
      workflow_execution_failed: 15,
      phase_execution_succeed: 150,
      phase_execution_failed: 80,
      phase_credit_succeed: 1000,
      phase_credit_failed: 85,
    },
    {
      date: new Date("2025-03-13"),
      workflow_execution_succeed: 40,
      workflow_execution_failed: 35,
      phase_execution_succeed: 140,
      phase_execution_failed: 85,
      phase_credit_succeed: 900,
      phase_credit_failed: 95,
    },
    {
      date: new Date("2025-03-12"),
      workflow_execution_succeed: 30,
      workflow_execution_failed: 40,
      phase_execution_succeed: 130,
      phase_execution_failed: 90,
      phase_credit_succeed: 800,
      phase_credit_failed: 105,
    },
    {
      date: new Date("2025-03-11"),
      workflow_execution_succeed: 20,
      workflow_execution_failed: 45,
      phase_execution_succeed: 120,
      phase_execution_failed: 95,
      phase_credit_succeed: 700,
      phase_credit_failed: 115,
    },
    {
      date: new Date("2025-03-10"),
      workflow_execution_succeed: 10,
      workflow_execution_failed: 50,
      phase_execution_succeed: 110,
      phase_execution_failed: 100,
      phase_credit_succeed: 600,
      phase_credit_failed: 125,
    },
  ],

  "Inventory Management Automation": [
    {
      date: new Date("2025-03-24"),
      workflow_execution_succeed: 80,
      workflow_execution_failed: 20,
      phase_execution_succeed: 200,
      phase_execution_failed: 30,
      phase_credit_succeed: 1100,
      phase_credit_failed: 100,
    },
    {
      date: new Date("2025-03-23"),
      workflow_execution_succeed: 60,
      workflow_execution_failed: 30,
      phase_execution_succeed: 190,
      phase_execution_failed: 35,
      phase_credit_succeed: 1000,
      phase_credit_failed: 120,
    },
    {
      date: new Date("2025-03-22"),
      workflow_execution_succeed: 90,
      workflow_execution_failed: 15,
      phase_execution_succeed: 180,
      phase_execution_failed: 40,
      phase_credit_succeed: 950,
      phase_credit_failed: 140,
    },
    {
      date: new Date("2025-03-21"),
      workflow_execution_succeed: 70,
      workflow_execution_failed: 25,
      phase_execution_succeed: 170,
      phase_execution_failed: 45,
      phase_credit_succeed: 900,
      phase_credit_failed: 150,
    },
    {
      date: new Date("2025-03-20"),
      workflow_execution_succeed: 80,
      workflow_execution_failed: 20,
      phase_execution_succeed: 160,
      phase_execution_failed: 50,
      phase_credit_succeed: 850,
      phase_credit_failed: 160,
    },
    {
      date: new Date("2025-03-19"),
      workflow_execution_succeed: 60,
      workflow_execution_failed: 30,
      phase_execution_succeed: 150,
      phase_execution_failed: 55,
      phase_credit_succeed: 800,
      phase_credit_failed: 170,
    },
    {
      date: new Date("2025-03-18"),
      workflow_execution_succeed: 100,
      workflow_execution_failed: 10,
      phase_execution_succeed: 140,
      phase_execution_failed: 60,
      phase_credit_succeed: 750,
      phase_credit_failed: 180,
    },
    {
      date: new Date("2025-03-17"),
      workflow_execution_succeed: 90,
      workflow_execution_failed: 15,
      phase_execution_succeed: 130,
      phase_execution_failed: 65,
      phase_credit_succeed: 700,
      phase_credit_failed: 190,
    },
    {
      date: new Date("2025-03-16"),
      workflow_execution_succeed: 110,
      workflow_execution_failed: 5,
      phase_execution_succeed: 120,
      phase_execution_failed: 70,
      phase_credit_succeed: 650,
      phase_credit_failed: 200,
    },
    {
      date: new Date("2025-03-15"),
      workflow_execution_succeed: 120,
      workflow_execution_failed: 10,
      phase_execution_succeed: 110,
      phase_execution_failed: 75,
      phase_credit_succeed: 600,
      phase_credit_failed: 210,
    },
    {
      date: new Date("2025-03-14"),
      workflow_execution_succeed: 90,
      workflow_execution_failed: 20,
      phase_execution_succeed: 100,
      phase_execution_failed: 80,
      phase_credit_succeed: 550,
      phase_credit_failed: 220,
    },
    {
      date: new Date("2025-03-13"),
      workflow_execution_succeed: 80,
      workflow_execution_failed: 30,
      phase_execution_succeed: 90,
      phase_execution_failed: 85,
      phase_credit_succeed: 500,
      phase_credit_failed: 230,
    },
    {
      date: new Date("2025-03-12"),
      workflow_execution_succeed: 70,
      workflow_execution_failed: 35,
      phase_execution_succeed: 80,
      phase_execution_failed: 90,
      phase_credit_succeed: 450,
      phase_credit_failed: 240,
    },
    {
      date: new Date("2025-03-11"),
      workflow_execution_succeed: 60,
      workflow_execution_failed: 40,
      phase_execution_succeed: 70,
      phase_execution_failed: 95,
      phase_credit_succeed: 400,
      phase_credit_failed: 250,
    },
    {
      date: new Date("2025-03-10"),
      workflow_execution_succeed: 50,
      workflow_execution_failed: 45,
      phase_execution_succeed: 60,
      phase_execution_failed: 100,
      phase_credit_succeed: 350,
      phase_credit_failed: 260,
    },
  ],

  "CRM Lead Nurturing Flow": [
    {
      date: new Date("2025-03-24"),
      workflow_execution_succeed: 80,
      workflow_execution_failed: 15,
      phase_execution_succeed: 160,
      phase_execution_failed: 30,
      phase_credit_succeed: 1100,
      phase_credit_failed: 120,
    },
    {
      date: new Date("2025-03-23"),
      workflow_execution_succeed: 90,
      workflow_execution_failed: 10,
      phase_execution_succeed: 150,
      phase_execution_failed: 35,
      phase_credit_succeed: 1000,
      phase_credit_failed: 140,
    },
    {
      date: new Date("2025-03-22"),
      workflow_execution_succeed: 70,
      workflow_execution_failed: 25,
      phase_execution_succeed: 140,
      phase_execution_failed: 40,
      phase_credit_succeed: 950,
      phase_credit_failed: 160,
    },
    {
      date: new Date("2025-03-21"),
      workflow_execution_succeed: 100,
      workflow_execution_failed: 5,
      phase_execution_succeed: 130,
      phase_execution_failed: 45,
      phase_credit_succeed: 900,
      phase_credit_failed: 180,
    },
    {
      date: new Date("2025-03-20"),
      workflow_execution_succeed: 80,
      workflow_execution_failed: 20,
      phase_execution_succeed: 120,
      phase_execution_failed: 50,
      phase_credit_succeed: 850,
      phase_credit_failed: 190,
    },
    {
      date: new Date("2025-03-19"),
      workflow_execution_succeed: 90,
      workflow_execution_failed: 10,
      phase_execution_succeed: 110,
      phase_execution_failed: 55,
      phase_credit_succeed: 800,
      phase_credit_failed: 200,
    },
    {
      date: new Date("2025-03-18"),
      workflow_execution_succeed: 60,
      workflow_execution_failed: 30,
      phase_execution_succeed: 100,
      phase_execution_failed: 60,
      phase_credit_succeed: 750,
      phase_credit_failed: 210,
    },
    {
      date: new Date("2025-03-17"),
      workflow_execution_succeed: 70,
      workflow_execution_failed: 25,
      phase_execution_succeed: 90,
      phase_execution_failed: 65,
      phase_credit_succeed: 700,
      phase_credit_failed: 220,
    },
    {
      date: new Date("2025-03-16"),
      workflow_execution_succeed: 50,
      workflow_execution_failed: 35,
      phase_execution_succeed: 80,
      phase_execution_failed: 70,
      phase_credit_succeed: 650,
      phase_credit_failed: 230,
    },
    {
      date: new Date("2025-03-15"),
      workflow_execution_succeed: 80,
      workflow_execution_failed: 15,
      phase_execution_succeed: 70,
      phase_execution_failed: 75,
      phase_credit_succeed: 600,
      phase_credit_failed: 240,
    },
    {
      date: new Date("2025-03-14"),
      workflow_execution_succeed: 90,
      workflow_execution_failed: 10,
      phase_execution_succeed: 60,
      phase_execution_failed: 80,
      phase_credit_succeed: 550,
      phase_credit_failed: 250,
    },
    {
      date: new Date("2025-03-13"),
      workflow_execution_succeed: 100,
      workflow_execution_failed: 5,
      phase_execution_succeed: 50,
      phase_execution_failed: 85,
      phase_credit_succeed: 500,
      phase_credit_failed: 260,
    },
    {
      date: new Date("2025-03-12"),
      workflow_execution_succeed: 110,
      workflow_execution_failed: 0,
      phase_execution_succeed: 40,
      phase_execution_failed: 90,
      phase_credit_succeed: 450,
      phase_credit_failed: 270,
    },
    {
      date: new Date("2025-03-11"),
      workflow_execution_succeed: 120,
      workflow_execution_failed: 0,
      phase_execution_succeed: 30,
      phase_execution_failed: 95,
      phase_credit_succeed: 400,
      phase_credit_failed: 280,
    },
    {
      date: new Date("2025-03-10"),
      workflow_execution_succeed: 130,
      workflow_execution_failed: 0,
      phase_execution_succeed: 20,
      phase_execution_failed: 100,
      phase_credit_succeed: 350,
      phase_credit_failed: 290,
    },
  ],

  "Customer Feedback Collection": [
    {
      date: new Date("2025-01-06"),
      workflow_execution_succeed: 45,
      workflow_execution_failed: 20,
      phase_execution_succeed: 170,
      phase_execution_failed: 25,
      phase_credit_succeed: 700,
      phase_credit_failed: 100,
    },
    {
      date: new Date("2025-01-13"),
      workflow_execution_succeed: 55,
      workflow_execution_failed: 18,
      phase_execution_succeed: 180,
      phase_execution_failed: 20,
      phase_credit_succeed: 750,
      phase_credit_failed: 90,
    },
    {
      date: new Date("2025-01-19"),
      workflow_execution_succeed: 60,
      workflow_execution_failed: 15,
      phase_execution_succeed: 190,
      phase_execution_failed: 18,
      phase_credit_succeed: 800,
      phase_credit_failed: 85,
    },
    {
      date: new Date("2025-01-27"),
      workflow_execution_succeed: 62,
      workflow_execution_failed: 13,
      phase_execution_succeed: 195,
      phase_execution_failed: 16,
      phase_credit_succeed: 810,
      phase_credit_failed: 80,
    },
    {
      date: new Date("2025-02-03"),
      workflow_execution_succeed: 66,
      workflow_execution_failed: 10,
      phase_execution_succeed: 205,
      phase_execution_failed: 14,
      phase_credit_succeed: 850,
      phase_credit_failed: 70,
    },
    {
      date: new Date("2025-02-09"),
      workflow_execution_succeed: 70,
      workflow_execution_failed: 8,
      phase_execution_succeed: 215,
      phase_execution_failed: 12,
      phase_credit_succeed: 880,
      phase_credit_failed: 60,
    },
    {
      date: new Date("2025-02-15"),
      workflow_execution_succeed: 75,
      workflow_execution_failed: 7,
      phase_execution_succeed: 230,
      phase_execution_failed: 10,
      phase_credit_succeed: 910,
      phase_credit_failed: 55,
    },
    {
      date: new Date("2025-02-21"),
      workflow_execution_succeed: 80,
      workflow_execution_failed: 5,
      phase_execution_succeed: 250,
      phase_execution_failed: 9,
      phase_credit_succeed: 940,
      phase_credit_failed: 45,
    },
    {
      date: new Date("2025-02-28"),
      workflow_execution_succeed: 85,
      workflow_execution_failed: 4,
      phase_execution_succeed: 265,
      phase_execution_failed: 7,
      phase_credit_succeed: 980,
      phase_credit_failed: 40,
    },
    {
      date: new Date("2025-03-03"),
      workflow_execution_succeed: 88,
      workflow_execution_failed: 3,
      phase_execution_succeed: 275,
      phase_execution_failed: 6,
      phase_credit_succeed: 1000,
      phase_credit_failed: 38,
    },
    {
      date: new Date("2025-03-08"),
      workflow_execution_succeed: 90,
      workflow_execution_failed: 3,
      phase_execution_succeed: 285,
      phase_execution_failed: 5,
      phase_credit_succeed: 1030,
      phase_credit_failed: 30,
    },
    {
      date: new Date("2025-03-12"),
      workflow_execution_succeed: 87,
      workflow_execution_failed: 4,
      phase_execution_succeed: 280,
      phase_execution_failed: 6,
      phase_credit_succeed: 1010,
      phase_credit_failed: 32,
    },
    {
      date: new Date("2025-03-16"),
      workflow_execution_succeed: 84,
      workflow_execution_failed: 5,
      phase_execution_succeed: 270,
      phase_execution_failed: 8,
      phase_credit_succeed: 980,
      phase_credit_failed: 40,
    },
    {
      date: new Date("2025-03-19"),
      workflow_execution_succeed: 81,
      workflow_execution_failed: 6,
      phase_execution_succeed: 260,
      phase_execution_failed: 10,
      phase_credit_succeed: 950,
      phase_credit_failed: 45,
    },
    {
      date: new Date("2025-03-22"),
      workflow_execution_succeed: 78,
      workflow_execution_failed: 8,
      phase_execution_succeed: 255,
      phase_execution_failed: 12,
      phase_credit_succeed: 910,
      phase_credit_failed: 55,
    },
  ],

  "Invoice Automation System": [
    {
      date: new Date("2025-01-02"),
      workflow_execution_succeed: 65,
      workflow_execution_failed: 20,
      phase_execution_succeed: 200,
      phase_execution_failed: 25,
      phase_credit_succeed: 950,
      phase_credit_failed: 110,
    },
    {
      date: new Date("2025-01-09"),
      workflow_execution_succeed: 70,
      workflow_execution_failed: 15,
      phase_execution_succeed: 215,
      phase_execution_failed: 20,
      phase_credit_succeed: 980,
      phase_credit_failed: 90,
    },
    {
      date: new Date("2025-01-16"),
      workflow_execution_succeed: 74,
      workflow_execution_failed: 12,
      phase_execution_succeed: 225,
      phase_execution_failed: 18,
      phase_credit_succeed: 1010,
      phase_credit_failed: 85,
    },
    {
      date: new Date("2025-01-23"),
      workflow_execution_succeed: 77,
      workflow_execution_failed: 10,
      phase_execution_succeed: 230,
      phase_execution_failed: 15,
      phase_credit_succeed: 1050,
      phase_credit_failed: 80,
    },
    {
      date: new Date("2025-01-30"),
      workflow_execution_succeed: 80,
      workflow_execution_failed: 8,
      phase_execution_succeed: 240,
      phase_execution_failed: 12,
      phase_credit_succeed: 1080,
      phase_credit_failed: 65,
    },
    {
      date: new Date("2025-02-05"),
      workflow_execution_succeed: 85,
      workflow_execution_failed: 6,
      phase_execution_succeed: 250,
      phase_execution_failed: 10,
      phase_credit_succeed: 1120,
      phase_credit_failed: 50,
    },
    {
      date: new Date("2025-02-11"),
      workflow_execution_succeed: 90,
      workflow_execution_failed: 5,
      phase_execution_succeed: 265,
      phase_execution_failed: 9,
      phase_credit_succeed: 1150,
      phase_credit_failed: 45,
    },
    {
      date: new Date("2025-02-17"),
      workflow_execution_succeed: 94,
      workflow_execution_failed: 4,
      phase_execution_succeed: 275,
      phase_execution_failed: 8,
      phase_credit_succeed: 1200,
      phase_credit_failed: 40,
    },
    {
      date: new Date("2025-02-23"),
      workflow_execution_succeed: 92,
      workflow_execution_failed: 5,
      phase_execution_succeed: 270,
      phase_execution_failed: 9,
      phase_credit_succeed: 1180,
      phase_credit_failed: 42,
    },
    {
      date: new Date("2025-02-29"),
      workflow_execution_succeed: 89,
      workflow_execution_failed: 6,
      phase_execution_succeed: 265,
      phase_execution_failed: 11,
      phase_credit_succeed: 1140,
      phase_credit_failed: 50,
    },
    {
      date: new Date("2025-03-04"),
      workflow_execution_succeed: 86,
      workflow_execution_failed: 7,
      phase_execution_succeed: 260,
      phase_execution_failed: 13,
      phase_credit_succeed: 1110,
      phase_credit_failed: 60,
    },
    {
      date: new Date("2025-03-09"),
      workflow_execution_succeed: 83,
      workflow_execution_failed: 9,
      phase_execution_succeed: 255,
      phase_execution_failed: 14,
      phase_credit_succeed: 1080,
      phase_credit_failed: 70,
    },
    {
      date: new Date("2025-03-13"),
      workflow_execution_succeed: 79,
      workflow_execution_failed: 10,
      phase_execution_succeed: 250,
      phase_execution_failed: 16,
      phase_credit_succeed: 1050,
      phase_credit_failed: 80,
    },
    {
      date: new Date("2025-03-17"),
      workflow_execution_succeed: 76,
      workflow_execution_failed: 11,
      phase_execution_succeed: 240,
      phase_execution_failed: 18,
      phase_credit_succeed: 1020,
      phase_credit_failed: 85,
    },
    {
      date: new Date("2025-03-21"),
      workflow_execution_succeed: 72,
      workflow_execution_failed: 13,
      phase_execution_succeed: 230,
      phase_execution_failed: 20,
      phase_credit_succeed: 990,
      phase_credit_failed: 90,
    },
  ],
};

export const getFakeStatData = () => {
  return [
    {
      date: subDays(Date.now(), 9),
      workflow_execution_succeed: 790,
      workflow_execution_failed: 100,
      phase_execution_succeed: 250,
      phase_execution_failed: 20,
      phase_credit_succeed: 950,
      phase_credit_failed: 55,
    },
    {
      date: subDays(Date.now(), 8),
      workflow_execution_succeed: 900,
      workflow_execution_failed: 359,
      phase_execution_succeed: 120,
      phase_execution_failed: 60,
      phase_credit_succeed: 860,
      phase_credit_failed: 90,
    },
    {
      date: subDays(Date.now(), 7),
      workflow_execution_succeed: 90,
      workflow_execution_failed: 15,
      phase_execution_succeed: 310,
      phase_execution_failed: 22,
      phase_credit_succeed: 1200,
      phase_credit_failed: 50,
    },
    {
      date: subDays(Date.now(), 6),
      workflow_execution_succeed: 25,
      workflow_execution_failed: 50,
      phase_execution_succeed: 80,
      phase_execution_failed: 70,
      phase_credit_succeed: 720,
      phase_credit_failed: 130,
    },
    {
      date: subDays(Date.now(), 5),
      workflow_execution_succeed: 60,
      workflow_execution_failed: 20,
      phase_execution_succeed: 240,
      phase_execution_failed: 28,
      phase_credit_succeed: 1010,
      phase_credit_failed: 65,
    },
    {
      date: subDays(Date.now(), 4),
      workflow_execution_succeed: 1510,
      workflow_execution_failed: 602,
      phase_execution_succeed: 95,
      phase_execution_failed: 80,
      phase_credit_succeed: 700,
      phase_credit_failed: 160,
    },
    {
      date: subDays(Date.now(), 3),
      workflow_execution_succeed: 1020,
      workflow_execution_failed: 42,
      phase_execution_succeed: 330,
      phase_execution_failed: 14,
      phase_credit_succeed: 1320,
      phase_credit_failed: 80,
    },
    {
      date: subDays(Date.now(), 2),
      workflow_execution_succeed: 493,
      workflow_execution_failed: 102,
      phase_execution_succeed: 11,
      phase_execution_failed: 499,
      phase_credit_succeed: 2034,
      phase_credit_failed: 199,
    },
    {
      date: startOfYesterday(),
      workflow_execution_succeed: 30,
      workflow_execution_failed: 80,
      phase_execution_succeed: 39,
      phase_execution_failed: 29,
      phase_credit_succeed: 1190,
      phase_credit_failed: 95,
    },
    {
      date: startOfToday(),
      workflow_execution_succeed: 30,
      workflow_execution_failed: 90,
      phase_execution_succeed: 305,
      phase_execution_failed: 20,
      phase_credit_succeed: 1180,
      phase_credit_failed: 100,
    },
  ];
};

export const folders: folderType[] = [
  {
    folderName: "Reports",
    folderColor: WORKFLOW_COLORS.indigo,
    folderPath: "r1e4t5s2", // Random ID
  },
  {
    folderName: "CRM Automation",
    folderColor: WORKFLOW_COLORS.blue,
    folderPath: "c5r3m1a2", // Random ID
  },
  {
    folderName: "Inventory",
    folderColor: WORKFLOW_COLORS.teal,
    folderPath: "i6n4v9t3r", // Random ID
  },
  {
    folderName: "Notifications",
    folderColor: WORKFLOW_COLORS.amber,
    folderPath: "n2o1t4s7", // Random ID
  },
  {
    folderName: "Marketing",
    folderColor: WORKFLOW_COLORS.slate,
    folderPath: "m9r8k5t1g", // Random ID
  },
  {
    folderName: "Email Campaigns",
    folderColor: WORKFLOW_COLORS.purple,
    folderPath: "e4m3c2p9s", // Random ID
  },
  {
    folderName: "Retention",
    folderColor: WORKFLOW_COLORS.red,
    folderPath: "r3e8t6n2", // Random ID
  },
  {
    folderName: "Social Media",
    folderColor: WORKFLOW_COLORS.yellow,
    folderPath: "s2m1d6a8", // Random ID
  },
  {
    folderName: "User Onboarding",
    folderColor: WORKFLOW_COLORS.green,
    folderPath: "u1o3b6n7", // Random ID
  },
  {
    folderName: "Backup & Security",
    folderColor: WORKFLOW_COLORS.slate,
    folderPath: "b7s3e8c9r", // Random ID
  },
  {
    folderName: "Finance",
    folderColor: WORKFLOW_COLORS.indigo,
    folderPath: "f9n1a5c2", // Random ID
  },
  {
    folderName: "Surveys",
    folderColor: WORKFLOW_COLORS.teal,
    folderPath: "s5r9e3y8s", // Random ID
  },
  {
    folderName: "DevOps",
    folderColor: WORKFLOW_COLORS.yellow,
    folderPath: "d7v3o2p9s", // Random ID
  },
];

export const fakeWorkflows: WorkflowCardType[] = [
  {
    title: "Daily Sales Report",
    creditCost: 10,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[0],
    isPinned: false,
    isActive: true,
    hasError: false,
    description:
      "Automated daily report that summarizes total sales and key metrics.",
    createdAt: new Date("2025-03-23"),
    updatedAt: new Date("2025-03-23"),
  },
  {
    title: "Lead Enrichment",
    creditCost: 15,
    triggerMode: "Webhook",
    state: "Published",
    folder: folders[1],
    isActive: true,
    hasError: false,
    description:
      "Enhance your CRM data with additional information about leads like company size, social profiles, and more.",
    createdAt: new Date("2025-01-10"),
    updatedAt: new Date("2025-01-10"),
  },
  {
    title: "Product Sync",
    creditCost: 8,
    triggerMode: "Manual",
    state: "Published",
    folder: folders[2],
    isPinned: false,
    isActive: true,
    hasError: false,
    description:
      "Keep your product catalog synced between your internal database and your e-commerce platforms.",
    createdAt: new Date("2024-12-18"),
    updatedAt: new Date("2025-01-07"),
  },
  {
    title: "New Order Alert",
    creditCost: 5,
    triggerMode: "Webhook",
    state: "Published",
    folder: folders[3],
    isPinned: true,
    isActive: true,
    hasError: false,
    description:
      "Instantly get notified when a new order is placed on your store.",
    createdAt: new Date("2025-01-02"),
    updatedAt: new Date("2025-01-14"),
  },
  {
    title: "Blog SEO Scan",
    creditCost: 12,
    triggerMode: "Manual",
    state: "Draft",
    folder: folders[4],
    isPinned: true,
    isActive: false,
    hasError: false,
    description:
      "Scan your blog content to identify SEO improvements such as keyword density, readability, and meta data suggestions.",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
  {
    title: "Weekly Email Digest",
    creditCost: 20,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[5],
    isPinned: true,
    isActive: true,
    hasError: true,
    description:
      "Send out a beautifully formatted weekly summary email to your subscribers with the top updates and content.",
    createdAt: new Date("2024-12-29"),
    updatedAt: new Date("2025-01-06"),
  },
  {
    title: "Abandoned Cart Reminder",
    creditCost: 18,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[6],
    isPinned: true,
    isActive: true,
    hasError: true,
    description:
      "Automatically remind users who left products in their cart to complete their purchase.",
    createdAt: new Date("2025-01-04"),
    updatedAt: new Date("2025-01-12"),
  },
  {
    title: "Instagram Auto Poster",
    creditCost: 25,
    triggerMode: "Manual",
    state: "Draft",
    folder: folders[7],
    isPinned: false,
    isActive: false,
    hasError: false,
    description:
      "Schedule and publish posts automatically to your Instagram account without manual intervention.",
    createdAt: new Date("2025-01-05"),
    updatedAt: new Date("2025-01-05"),
  },
  {
    title: "New User Welcome",
    creditCost: 7,
    triggerMode: "Webhook",
    state: "Published",
    folder: folders[8],
    isPinned: false,
    isActive: true,
    hasError: true,
    description:
      "Deliver a warm welcome to new users and guide them through your onboarding steps.",
    createdAt: new Date("2025-01-07"),
    updatedAt: new Date("2025-01-13"),
  },
  {
    title: "Backup to Google Drive",
    creditCost: 11,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[9],
    isPinned: true,
    isActive: true,
    hasError: false,
    description:
      "Automatically backup your critical files and data to a secure Google Drive folder every day.",
    createdAt: new Date("2024-12-22"),
    updatedAt: new Date("2025-01-02"),
  },
  {
    title: "Invoice Generator",
    creditCost: 9,
    triggerMode: "Manual",
    state: "Published",
    folder: folders[10],
    isPinned: false,
    isActive: true,
    hasError: false,
    description:
      "Generate professional-looking invoices on the fly and send them to your clients with just a few clicks.",
    createdAt: new Date("2024-12-28"),
    updatedAt: new Date("2025-01-11"),
  },
  {
    title: "Feedback Collector",
    creditCost: 6,
    triggerMode: "Webhook",
    state: "Draft",
    folder: folders[11],
    isPinned: true,
    isActive: false,
    hasError: true,
    description:
      "Capture customer feedback at key touchpoints and analyze sentiment for continuous improvement.",
    createdAt: new Date("2025-01-08"),
    updatedAt: new Date("2025-01-08"),
  },
  {
    title: "Server Health Monitor",
    creditCost: 14,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[12],
    isPinned: true,
    isActive: true,
    hasError: false,
    description:
      "Monitor your server uptime, performance metrics, and receive real-time alerts for anomalies.",
    createdAt: new Date("2025-01-03"),
    updatedAt: new Date("2025-01-14"),
  },
  {
    title: "Monthly Revenue Snapshot",
    creditCost: 13,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[0],
    isPinned: false,
    isActive: true,
    hasError: false,
    description:
      "Get a clean snapshot of your monthly revenue, broken down by product, region, and sales channel.",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-10"),
  },
  {
    title: "Product Performance Report",
    creditCost: 10,
    triggerMode: "Manual",
    state: "Published",
    folder: folders[0],
    isPinned: true,
    isActive: true,
    hasError: false,
    description:
      "Analyze how each product is performing over time in terms of revenue, engagement, and returns.",
    createdAt: new Date("2025-01-02"),
    updatedAt: new Date("2025-01-12"),
  },
  {
    title: "User Growth Report",
    creditCost: 12,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[0],
    isPinned: false,
    isActive: true,
    hasError: false,
    description:
      "Measure user acquisition trends and growth rate across different time periods.",
    createdAt: new Date("2025-01-03"),
    updatedAt: new Date("2025-01-13"),
  },
  {
    title: "Sales Team Performance",
    creditCost: 16,
    triggerMode: "Scheduled",
    state: "Draft",
    folder: folders[0],
    isPinned: false,
    isActive: false,
    hasError: false,
    description:
      "Compare the performance of your sales team members by deal value, close rate, and response time.",
    createdAt: new Date("2025-01-04"),
    updatedAt: new Date("2025-01-04"),
  },
  {
    title: "CRM Contact Sync",
    creditCost: 10,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[1],
    isPinned: true,
    isActive: true,
    hasError: true,
    description:
      "Ensure your CRM contact database stays updated with the latest changes from your other tools.",
    createdAt: new Date("2025-01-06"),
    updatedAt: new Date("2025-01-14"),
  },
  {
    title: "Duplicate Contact Cleaner",
    creditCost: 8,
    triggerMode: "Manual",
    state: "Draft",
    folder: folders[1],
    isPinned: false,
    isActive: false,
    hasError: false,
    description:
      "Identify and merge duplicate contact entries in your CRM system to maintain data cleanliness.",
    createdAt: new Date("2025-01-03"),
    updatedAt: new Date("2025-01-03"),
  },
  {
    title: "Lead Scoring Bot",
    creditCost: 18,
    triggerMode: "Webhook",
    state: "Published",
    folder: folders[1],
    isPinned: false,
    isActive: true,
    hasError: true,
    description:
      "Automatically score leads based on custom rules and behavior to prioritize follow-ups.",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-12"),
  },
  {
    title: "Customer Segmentation",
    creditCost: 14,
    triggerMode: "Manual",
    state: "Published",
    folder: folders[2],
    isPinned: false,
    isActive: true,
    hasError: false,
    description:
      "Segment your customers dynamically based on behavior, purchase history, and demographics.",
    createdAt: new Date("2025-01-04"),
    updatedAt: new Date("2025-01-09"),
  },
  {
    title: "Inventory Tracker",
    creditCost: 17,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[2],
    isPinned: true,
    isActive: true,
    hasError: true,
    description:
      "Track your product inventory levels across warehouses and receive alerts for low stock.",
    createdAt: new Date("2024-12-31"),
    updatedAt: new Date("2025-01-11"),
  },
  {
    title: "Order Status Notifier",
    creditCost: 6,
    triggerMode: "Webhook",
    state: "Published",
    folder: folders[3],
    isPinned: false,
    isActive: true,
    hasError: false,
    description:
      "Send real-time updates to customers about their order processing and delivery status.",
    createdAt: new Date("2025-01-05"),
    updatedAt: new Date("2025-01-07"),
  },
  {
    title: "New Review Alert",
    creditCost: 5,
    triggerMode: "Webhook",
    state: "Published",
    folder: folders[4],
    isPinned: true,
    isActive: true,
    hasError: false,
    description:
      "Get instantly notified when a new review is submitted on your product pages.",
    createdAt: new Date("2025-01-02"),
    updatedAt: new Date("2025-01-02"),
  },
  {
    title: "Affiliate Performance Report",
    creditCost: 13,
    triggerMode: "Manual",
    state: "Published",
    folder: folders[5],
    isPinned: false,
    isActive: true,
    hasError: false,
    description:
      "Track performance of each affiliate partner including clicks, conversions, and payouts.",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-12"),
  },
  {
    title: "Customer Support Analyzer",
    creditCost: 15,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[6],
    isPinned: true,
    isActive: true,
    hasError: true,
    description:
      "Analyze customer support tickets for common issues and agent performance.",
    createdAt: new Date("2024-12-30"),
    updatedAt: new Date("2025-01-10"),
  },
  {
    title: "Coupon Usage Tracker",
    creditCost: 7,
    triggerMode: "Manual",
    state: "Draft",
    folder: folders[7],
    isPinned: false,
    isActive: false,
    hasError: false,
    description:
      "Monitor how customers are using discount codes and identify top-performing promotions.",
    createdAt: new Date("2025-01-06"),
    updatedAt: new Date("2025-01-06"),
  },
  {
    title: "Churn Risk Detector",
    creditCost: 20,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[8],
    isPinned: true,
    isActive: true,
    hasError: false,
    description:
      "Predict which users are likely to churn based on behavior and engagement patterns.",
    createdAt: new Date("2025-01-07"),
    updatedAt: new Date("2025-01-14"),
  },
  {
    title: "Social Mentions Tracker",
    creditCost: 11,
    triggerMode: "Webhook",
    state: "Published",
    folder: folders[9],
    isPinned: false,
    isActive: true,
    hasError: true,
    description:
      "Track mentions of your brand across social media platforms in real time.",
    createdAt: new Date("2025-01-03"),
    updatedAt: new Date("2025-01-09"),
  },
  {
    title: "VIP Customer Monitor",
    creditCost: 9,
    triggerMode: "Scheduled",
    state: "Published",
    folder: folders[10],
    isPinned: false,
    isActive: true,
    hasError: false,
    description:
      "Keep track of your most valuable customers and get alerts on their activity.",
    createdAt: new Date("2025-01-05"),
    updatedAt: new Date("2025-01-11"),
  },
  {
    title: "Refund Pattern Detector",
    creditCost: 12,
    triggerMode: "Scheduled",
    state: "Draft",
    folder: folders[11],
    isPinned: false,
    isActive: false,
    hasError: false,
    description:
      "Identify patterns in product returns and refunds to detect potential product issues.",
    createdAt: new Date("2025-01-04"),
    updatedAt: new Date("2025-01-04"),
  },
  {
    title: "Campaign ROI Calculator",
    creditCost: 13,
    triggerMode: "Manual",
    state: "Published",
    folder: folders[12],
    isPinned: true,
    isActive: true,
    hasError: false,
    description:
      "Calculate return on investment for each of your marketing campaigns using real-time data.",
    createdAt: new Date("2024-12-29"),
    updatedAt: new Date("2025-01-08"),
  },
  {
    title: "Data Sync Audit",
    creditCost: 8,
    triggerMode: "Manual",
    state: "Published",
    folder: folders[0],
    isPinned: false,
    isActive: true,
    hasError: false,
    description:
      "Run audits to detect data mismatches and sync failures between connected systems.",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-13"),
  },
  {
    title: "Form Submissions Collector",
    creditCost: 10,
    triggerMode: "Webhook",
    state: "Published",
    folder: folders[1],
    isPinned: true,
    isActive: true,
    hasError: false,
    description:
      "Collect and organize all form submissions from your site into a central dashboard.",
    createdAt: new Date("2025-01-02"),
    updatedAt: new Date("2025-01-10"),
  },
];

export const fakeImportedFiles: importedFile[] = [
  {
    name: "product_data.json",
    importedAt: new Date("2025-03-20T10:15:00Z"),
    fileCategory: "Workflow",
    fileType: "json",
    fileSizeInBytes: 20480,
    isSafe: true,
  },
  {
    name: "seo_guide.md",
    importedAt: new Date("2025-03-21T14:30:00Z"),
    fileCategory: "Knowledge Base",
    fileType: "markdown",
    fileSizeInBytes: 10240,
    isSafe: true,
  },
  {
    name: "customer_faq.txt",
    importedAt: new Date("2025-03-18T08:45:00Z"),
    fileCategory: "Knowledge Base",
    fileType: "txt",
    fileSizeInBytes: 5120,
    isSafe: true,
  },
  {
    name: "workflow_config.json",
    importedAt: new Date("2025-03-22T16:10:00Z"),
    fileCategory: "Workflow",
    fileType: "json",
    fileSizeInBytes: 30720,
    isSafe: true,
  },
  {
    name: "user_guide.html",
    importedAt: new Date("2025-03-19T11:20:00Z"),
    fileCategory: "Knowledge Base",
    fileType: "html",
    fileSizeInBytes: 25600,
    isSafe: true,
  },
  {
    name: "api_reference.md",
    importedAt: new Date("2025-03-17T09:00:00Z"),
    fileCategory: "Knowledge Base",
    fileType: "markdown",
    fileSizeInBytes: 153000260,
    isSafe: true,
  },
  {
    name: "site_backup.json",
    importedAt: new Date("2025-03-15T07:45:00Z"),
    fileCategory: "Workflow",
    fileType: "json",
    fileSizeInBytes: 51200,
    isSafe: true,
  },
  {
    name: "terms_of_service.txt",
    importedAt: new Date("2025-03-14T13:25:00Z"),
    fileCategory: "Knowledge Base",
    fileType: "txt",
    fileSizeInBytes: 8192,
    isSafe: true,
  },
  {
    name: "project_automation.json",
    importedAt: new Date("2025-03-16T18:55:00Z"),
    fileCategory: "Workflow",
    fileType: "json",
    fileSizeInBytes: 40960,
    isSafe: true,
  },
  {
    name: "business_strategy.md",
    importedAt: new Date("2025-03-23T20:30:00Z"),
    fileCategory: "Knowledge Base",
    fileType: "markdown",
    fileSizeInBytes: 12288,
    isSafe: true,
  },
  {
    name: "website_structure.html",
    importedAt: new Date("2025-03-20T15:40:00Z"),
    fileCategory: "Knowledge Base",
    fileType: "html",
    fileSizeInBytes: 34816,
    isSafe: true,
  },
  {
    name: "email_campaign_workflow.json",
    importedAt: new Date("2025-03-24T09:10:00Z"),
    fileCategory: "Workflow",
    fileType: "json",
    fileSizeInBytes: 28672,
    isSafe: true,
  },
  {
    name: "important_notes.txt",
    importedAt: new Date("2025-01-22T22:15:00Z"),
    fileCategory: "Knowledge Base",
    fileType: "txt",
    fileSizeInBytes: 4096,
    isSafe: true,
  },
];
